/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_BDD_PB2_PB_H_INCLUDED
#define PB_BDD_PB2_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _bdd_nodePowerMode {
    bdd_nodePowerMode_SLAVE_BUS_POWERED = 0,
    bdd_nodePowerMode_SLAVE_LOCAL_POWERED = 1
} bdd_nodePowerMode;

typedef enum _bdd_highPwrSwitchCfg {
    bdd_highPwrSwitchCfg_HPSW_CFG_0 = 0,
    bdd_highPwrSwitchCfg_HPSW_CFG_1 = 1,
    bdd_highPwrSwitchCfg_HPSW_CFG_4 = 4
} bdd_highPwrSwitchCfg;

typedef enum _bdd_NodeType {
    bdd_NODE_TYPE_UNKNOWN = 0,
    bdd_NODE_TYPE_MASTER = 1,
    bdd_NODE_TYPE_SLAVE = 2
} bdd_NodeType;

typedef enum _bdd_DiscoveryMode {
    bdd_DISCOVERY_MODE_SIMPLE = 0,
    bdd_DISCOVERY_MODE_MODIFIED = 1,
    bdd_DISCOVERY_MODE_OPTIMIZED = 2,
    bdd_DISCOVERY_MODE_ADVANCED = 3
} bdd_DiscoveryMode;

typedef enum _bdd_ConfigMethod {
    bdd_CONFIG_METHOD_AUTO = 0,
    bdd_CONFIG_METHOD_BDD = 1,
    bdd_CONFIG_METHOD_HYBRID = 2
} bdd_ConfigMethod;

typedef enum _bdd_ConfigPriority {
    bdd_CONFIG_PRIORITY_AUTO = 0,
    bdd_CONFIG_PRIORITY_BDD = 1
} bdd_ConfigPriority;

typedef enum _bdd_ConfigErrPolicy {
    bdd_CONFIG_ERR_POLICY_FATAL = 0,
    bdd_CONFIG_ERR_POLICY_ERROR = 1,
    bdd_CONFIG_ERR_POLICY_WARN = 2,
    bdd_CONFIG_ERR_POLCIY_NONE = 3
} bdd_ConfigErrPolicy;

typedef enum _bdd_A2bDeviceInterface {
    bdd_A2bDeviceInterface_I2C = 0,
    bdd_A2bDeviceInterface_SPI = 1
} bdd_A2bDeviceInterface;

typedef enum _bdd_A2bCableType {
    bdd_A2bCableType_UTP = 0,
    bdd_A2bCableType_XLR = 1,
    bdd_A2bCableType_RJ45 = 2
} bdd_A2bCableType;

/* Struct definitions */
typedef struct _bdd_MetaData {
    uint32_t date;
    uint32_t version;
    bool has_author;
    char author[64];
    bool has_organization;
    char organization[64];
    bool has_company;
    char company[64];
    bool has_bddVersion;
    uint32_t bddVersion;
} bdd_MetaData;

typedef struct _bdd_CustomNodeIdSettings {
    bool has_bCustomNodeIdAuth;
    uint32_t bCustomNodeIdAuth;
    bool has_bReadFrmMemory;
    uint32_t bReadFrmMemory;
    bool has_bReadFrmCommCh;
    uint32_t bReadFrmCommCh;
    bool has_nDeviceAddr;
    uint32_t nDeviceAddr;
    bool has_nNodeId;
    char nNodeId[64];
    bool has_nNodeIdLength;
    uint32_t nNodeIdLength;
    bool has_nReadMemAddrWidth;
    uint32_t nReadMemAddrWidth;
    bool has_nReadMemAddr;
    uint32_t nReadMemAddr;
    bool has_bReadGpioPins;
    uint32_t bReadGpioPins;
    pb_size_t aGpio_count;
    uint32_t aGpio[8];
    bool has_nTimeOut;
    uint32_t nTimeOut;
    bool has_nRetryCnt;
    uint32_t nRetryCnt;
} bdd_CustomNodeIdSettings;

typedef struct _bdd_NodeDescriptor {
    uint32_t vendor;
    uint32_t product;
    uint32_t version;
    bool has_oCustomNodeIdSettings;
    bdd_CustomNodeIdSettings oCustomNodeIdSettings;
    bool has_btwoStepDisc;
    uint32_t btwoStepDisc;
} bdd_NodeDescriptor;

typedef struct _bdd_CtrlRegs {
    bool has_bcdnslots;
    uint32_t bcdnslots;
    bool has_ldnslots;
    uint32_t ldnslots;
    bool has_lupslots;
    uint32_t lupslots;
    bool has_dnslots;
    uint32_t dnslots;
    bool has_upslots;
    uint32_t upslots;
    bool has_respcycs;
    uint32_t respcycs;
    bool has_slotfmt;
    uint32_t slotfmt;
    bool has_suscfg;
    uint32_t suscfg;
    bool has_datctl;
    uint32_t datctl;
    bool has_control;
    uint32_t control;
    bool has_swctl;
    uint32_t swctl;
    bool has_swctl2;
    uint32_t swctl2;
    bool has_swctl3;
    uint32_t swctl3;
    bool has_swctl4;
    uint32_t swctl4;
    bool has_swctl5;
    uint32_t swctl5;
    bool has_swctl6;
    uint32_t swctl6;
} bdd_CtrlRegs;

typedef struct _bdd_VmtrRegs {
    bool has_vmtr_ven;
    uint32_t vmtr_ven;
    bool has_vmtr_inten;
    uint32_t vmtr_inten;
    bool has_vmtr_mxstat;
    uint32_t vmtr_mxstat;
    bool has_vmtr_mnstat;
    uint32_t vmtr_mnstat;
    bool has_vmtr_vmax0;
    uint32_t vmtr_vmax0;
    bool has_vmtr_vmin0;
    uint32_t vmtr_vmin0;
    bool has_vmtr_vmax1;
    uint32_t vmtr_vmax1;
    bool has_vmtr_vmin1;
    uint32_t vmtr_vmin1;
    bool has_vmtr_vmax2;
    uint32_t vmtr_vmax2;
    bool has_vmtr_vmin2;
    uint32_t vmtr_vmin2;
    bool has_vmtr_vmax3;
    uint32_t vmtr_vmax3;
    bool has_vmtr_vmin3;
    uint32_t vmtr_vmin3;
    bool has_vmtr_vmax4;
    uint32_t vmtr_vmax4;
    bool has_vmtr_vmin4;
    uint32_t vmtr_vmin4;
    bool has_vmtr_vmax5;
    uint32_t vmtr_vmax5;
    bool has_vmtr_vmin5;
    uint32_t vmtr_vmin5;
    bool has_vmtr_vmax6;
    uint32_t vmtr_vmax6;
    bool has_vmtr_vmin6;
    uint32_t vmtr_vmin6;
} bdd_VmtrRegs;

typedef struct _bdd_I2sCrossbarRegs {
    bool has_has_rxmask;
    bool has_rxmask;
    pb_size_t rxmask_count;
    uint32_t rxmask[8];
    bool has_has_txcrossbar;
    bool has_txcrossbar;
    pb_size_t txcrossbar_count;
    uint32_t txcrossbar[32];
} bdd_I2sCrossbarRegs;

typedef struct _bdd_PwmRegs {
    bool has_pwmcfg;
    uint32_t pwmcfg;
    bool has_pwmfreq;
    uint32_t pwmfreq;
    bool has_pwmblink1;
    uint32_t pwmblink1;
    bool has_pwmblink2;
    uint32_t pwmblink2;
    bool has_has_pwmval;
    bool has_pwmval;
    pb_size_t pwmval_count;
    uint32_t pwmval[6];
    bool has_has_pwmoe;
    bool has_pwmoe;
    pb_size_t pwmoe_count;
    uint32_t pwmoe[2];
} bdd_PwmRegs;

typedef struct _bdd_SpiRegs {
    bool has_spicfg;
    uint32_t spicfg;
    bool has_spickdiv;
    uint32_t spickdiv;
    bool has_spifdsize;
    uint32_t spifdsize;
    bool has_spifdtarg;
    uint32_t spifdtarg;
    bool has_spipicfg;
    uint32_t spipicfg;
    bool has_spiint;
    uint32_t spiint;
    bool has_spimsk;
    uint32_t spimsk;
} bdd_SpiRegs;

typedef struct _bdd_DataTunnelRegs {
    bool has_dtcfg;
    uint32_t dtcfg;
    bool has_dtslots;
    uint32_t dtslots;
    bool has_dtndnoffs;
    uint32_t dtndnoffs;
    bool has_dtnupoffs;
    uint32_t dtnupoffs;
} bdd_DataTunnelRegs;

typedef struct _bdd_IntRegs {
    bool has_intmsk0;
    uint32_t intmsk0;
    bool has_intmsk1;
    uint32_t intmsk1;
    bool has_intmsk2;
    uint32_t intmsk2;
    bool has_becctl;
    uint32_t becctl;
} bdd_IntRegs;

typedef struct _bdd_TuningRegs {
    bool has_vregctl;
    uint32_t vregctl;
    bool has_txactl;
    uint32_t txactl;
    bool has_rxactl;
    uint32_t rxactl;
    bool has_txbctl;
    uint32_t txbctl;
    bool has_rxbctl;
    uint32_t rxbctl;
    bool has_txctl;
    uint32_t txctl;
    bool has_rxctl;
    uint32_t rxctl;
} bdd_TuningRegs;

typedef struct _bdd_I2cI2sRegs {
    bool has_i2ccfg;
    uint32_t i2ccfg;
    bool has_pllctl;
    uint32_t pllctl;
    bool has_i2sgcfg;
    uint32_t i2sgcfg;
    bool has_i2scfg;
    uint32_t i2scfg;
    bool has_i2srate;
    uint32_t i2srate;
    bool has_i2stxoffset;
    uint32_t i2stxoffset;
    bool has_i2srxoffset;
    uint32_t i2srxoffset;
    bool has_syncoffset;
    uint32_t syncoffset;
    bool has_pdmctl;
    uint32_t pdmctl;
    bool has_errmgmt;
    uint32_t errmgmt;
    bool has_i2srrate;
    uint32_t i2srrate;
    bool has_i2srrctl;
    uint32_t i2srrctl;
    bool has_i2srrsoffs;
    uint32_t i2srrsoffs;
    bool has_pdmctl2;
    uint32_t pdmctl2;
    bool has_i2stest;
    uint32_t i2stest;
} bdd_I2cI2sRegs;

typedef struct _bdd_PinIoRegs {
    bool has_clkcfg;
    uint32_t clkcfg;
    bool has_gpiooen;
    uint32_t gpiooen;
    bool has_gpioien;
    uint32_t gpioien;
    bool has_pinten;
    uint32_t pinten;
    bool has_pintinv;
    uint32_t pintinv;
    bool has_pincfg;
    uint32_t pincfg;
    bool has_gpiodat;
    uint32_t gpiodat;
    bool has_clk1cfg;
    uint32_t clk1cfg;
    bool has_clk2cfg;
    uint32_t clk2cfg;
} bdd_PinIoRegs;

typedef struct _bdd_DataSlotEnhancementRegs {
    bool has_upmask0;
    uint32_t upmask0;
    bool has_upmask1;
    uint32_t upmask1;
    bool has_upmask2;
    uint32_t upmask2;
    bool has_upmask3;
    uint32_t upmask3;
    bool has_upoffset;
    uint32_t upoffset;
    bool has_dnmask0;
    uint32_t dnmask0;
    bool has_dnmask1;
    uint32_t dnmask1;
    bool has_dnmask2;
    uint32_t dnmask2;
    bool has_dnmask3;
    uint32_t dnmask3;
    bool has_dnoffset;
    uint32_t dnoffset;
} bdd_DataSlotEnhancementRegs;

typedef struct _bdd_GpioDRegs {
    bool has_gpioden;
    uint32_t gpioden;
    bool has_gpiod0msk;
    uint32_t gpiod0msk;
    bool has_gpiod1msk;
    uint32_t gpiod1msk;
    bool has_gpiod2msk;
    uint32_t gpiod2msk;
    bool has_gpiod3msk;
    uint32_t gpiod3msk;
    bool has_gpiod4msk;
    uint32_t gpiod4msk;
    bool has_gpiod5msk;
    uint32_t gpiod5msk;
    bool has_gpiod6msk;
    uint32_t gpiod6msk;
    bool has_gpiod7msk;
    uint32_t gpiod7msk;
    bool has_gpioddat;
    uint32_t gpioddat;
    bool has_gpiodinv;
    uint32_t gpiodinv;
} bdd_GpioDRegs;

typedef struct _bdd_MailboxRegs {
    bool has_mbox0ctl;
    uint32_t mbox0ctl;
    bool has_mbox1ctl;
    uint32_t mbox1ctl;
} bdd_MailboxRegs;

typedef struct _bdd_DebugRegs {
    bool has_debugReg1;
    uint32_t debugReg1;
    bool has_debugReg2;
    uint32_t debugReg2;
    bool has_debugReg3;
    uint32_t debugReg3;
    bool has_debugReg4;
    uint32_t debugReg4;
    bool has_debugReg5;
    uint32_t debugReg5;
    bool has_debugReg6;
    uint32_t debugReg6;
    bool has_debugReg7;
    uint32_t debugReg7;
    bool has_debugReg8;
    uint32_t debugReg8;
    bool has_debugReg9;
    uint32_t debugReg9;
    bool has_debugReg10;
    uint32_t debugReg10;
} bdd_DebugRegs;

typedef struct _bdd_NodeSettings {
    bool has_bLocalPwrd;
    bdd_nodePowerMode bLocalPwrd;
    bool has_eHighPwrSwitchCfg;
    bdd_highPwrSwitchCfg eHighPwrSwitchCfg;
} bdd_NodeSettings;

typedef struct _bdd_Node {
    bdd_NodeType nodeType;
    bdd_CtrlRegs ctrlRegs;
    bool has_intRegs;
    bdd_IntRegs intRegs;
    bool has_tuningRegs;
    bdd_TuningRegs tuningRegs;
    bdd_I2cI2sRegs i2cI2sRegs;
    bdd_PinIoRegs pinIoRegs;
    bool ignEeprom;
    bool verifyNodeDescr;
    bdd_NodeDescriptor nodeDescr;
    uint32_t downstreamBcastCnt;
    pb_size_t downstream_count;
    uint32_t downstream[32];
    uint32_t upstreamBcastCnt;
    pb_size_t upstream_count;
    uint32_t upstream[32];
    bool has_slotEnh;
    bdd_DataSlotEnhancementRegs slotEnh;
    bool has_gpioDist;
    bdd_GpioDRegs gpioDist;
    bool has_mbox;
    bdd_MailboxRegs mbox;
    bool has_i2sCrossbarRegs;
    bdd_I2sCrossbarRegs i2sCrossbarRegs;
    bool has_pwmRegs;
    bdd_PwmRegs pwmRegs;
    bool has_spiRegs;
    bdd_SpiRegs spiRegs;
    bool has_dataTunnelRegs;
    bdd_DataTunnelRegs dataTunnelRegs;
    bool has_vmtrRegs;
    bdd_VmtrRegs vmtrRegs;
    bool has_debugReg;
    bdd_DebugRegs debugReg;
    bool has_nodeSetting;
    bdd_NodeSettings nodeSetting;
} bdd_Node;

typedef struct _bdd_NetworkPolicy {
    bdd_DiscoveryMode discoveryMode;
    bdd_ConfigMethod cfgMethod;
    bdd_ConfigPriority cfgPriority;
    bdd_ConfigErrPolicy cfgErrPolicy;
    bool has_has_common_SSSettings;
    bool has_common_SSSettings;
    bool has_discoveryStartDelay;
    uint32_t discoveryStartDelay;
    bool has_bOverrideSelfDisc;
    bool bOverrideSelfDisc;
    bool has_bCrossTalkFixApply;
    bool bCrossTalkFixApply;
    bool has_nRediscWaitTime;
    uint32_t nRediscWaitTime;
    bool has_bEnablePartialDisc;
    bool bEnablePartialDisc;
    bool has_eA2bDeviceInterface;
    bdd_A2bDeviceInterface eA2bDeviceInterface;
    bool has_eCableType;
    bdd_A2bCableType eCableType;
} bdd_NetworkPolicy;

typedef struct _bdd_Network {
    bdd_MetaData metaData;
    uint32_t masterAddr;
    bdd_NetworkPolicy policy;
    pb_size_t nodes_count;
    bdd_Node nodes[17];
    uint32_t sampleRate;
} bdd_Network;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _bdd_nodePowerMode_MIN bdd_nodePowerMode_SLAVE_BUS_POWERED
#define _bdd_nodePowerMode_MAX bdd_nodePowerMode_SLAVE_LOCAL_POWERED
#define _bdd_nodePowerMode_ARRAYSIZE ((bdd_nodePowerMode)(bdd_nodePowerMode_SLAVE_LOCAL_POWERED+1))

#define _bdd_highPwrSwitchCfg_MIN bdd_highPwrSwitchCfg_HPSW_CFG_0
#define _bdd_highPwrSwitchCfg_MAX bdd_highPwrSwitchCfg_HPSW_CFG_4
#define _bdd_highPwrSwitchCfg_ARRAYSIZE ((bdd_highPwrSwitchCfg)(bdd_highPwrSwitchCfg_HPSW_CFG_4+1))

#define _bdd_NodeType_MIN bdd_NODE_TYPE_UNKNOWN
#define _bdd_NodeType_MAX bdd_NODE_TYPE_SLAVE
#define _bdd_NodeType_ARRAYSIZE ((bdd_NodeType)(bdd_NODE_TYPE_SLAVE+1))
#define bdd_NodeType_NODE_TYPE_UNKNOWN bdd_NODE_TYPE_UNKNOWN
#define bdd_NodeType_NODE_TYPE_MASTER bdd_NODE_TYPE_MASTER
#define bdd_NodeType_NODE_TYPE_SLAVE bdd_NODE_TYPE_SLAVE

#define _bdd_DiscoveryMode_MIN bdd_DISCOVERY_MODE_SIMPLE
#define _bdd_DiscoveryMode_MAX bdd_DISCOVERY_MODE_ADVANCED
#define _bdd_DiscoveryMode_ARRAYSIZE ((bdd_DiscoveryMode)(bdd_DISCOVERY_MODE_ADVANCED+1))
#define bdd_DiscoveryMode_DISCOVERY_MODE_SIMPLE bdd_DISCOVERY_MODE_SIMPLE
#define bdd_DiscoveryMode_DISCOVERY_MODE_MODIFIED bdd_DISCOVERY_MODE_MODIFIED
#define bdd_DiscoveryMode_DISCOVERY_MODE_OPTIMIZED bdd_DISCOVERY_MODE_OPTIMIZED
#define bdd_DiscoveryMode_DISCOVERY_MODE_ADVANCED bdd_DISCOVERY_MODE_ADVANCED

#define _bdd_ConfigMethod_MIN bdd_CONFIG_METHOD_AUTO
#define _bdd_ConfigMethod_MAX bdd_CONFIG_METHOD_HYBRID
#define _bdd_ConfigMethod_ARRAYSIZE ((bdd_ConfigMethod)(bdd_CONFIG_METHOD_HYBRID+1))
#define bdd_ConfigMethod_CONFIG_METHOD_AUTO bdd_CONFIG_METHOD_AUTO
#define bdd_ConfigMethod_CONFIG_METHOD_BDD bdd_CONFIG_METHOD_BDD
#define bdd_ConfigMethod_CONFIG_METHOD_HYBRID bdd_CONFIG_METHOD_HYBRID

#define _bdd_ConfigPriority_MIN bdd_CONFIG_PRIORITY_AUTO
#define _bdd_ConfigPriority_MAX bdd_CONFIG_PRIORITY_BDD
#define _bdd_ConfigPriority_ARRAYSIZE ((bdd_ConfigPriority)(bdd_CONFIG_PRIORITY_BDD+1))
#define bdd_ConfigPriority_CONFIG_PRIORITY_AUTO bdd_CONFIG_PRIORITY_AUTO
#define bdd_ConfigPriority_CONFIG_PRIORITY_BDD bdd_CONFIG_PRIORITY_BDD

#define _bdd_ConfigErrPolicy_MIN bdd_CONFIG_ERR_POLICY_FATAL
#define _bdd_ConfigErrPolicy_MAX bdd_CONFIG_ERR_POLCIY_NONE
#define _bdd_ConfigErrPolicy_ARRAYSIZE ((bdd_ConfigErrPolicy)(bdd_CONFIG_ERR_POLCIY_NONE+1))
#define bdd_ConfigErrPolicy_CONFIG_ERR_POLICY_FATAL bdd_CONFIG_ERR_POLICY_FATAL
#define bdd_ConfigErrPolicy_CONFIG_ERR_POLICY_ERROR bdd_CONFIG_ERR_POLICY_ERROR
#define bdd_ConfigErrPolicy_CONFIG_ERR_POLICY_WARN bdd_CONFIG_ERR_POLICY_WARN
#define bdd_ConfigErrPolicy_CONFIG_ERR_POLCIY_NONE bdd_CONFIG_ERR_POLCIY_NONE

#define _bdd_A2bDeviceInterface_MIN bdd_A2bDeviceInterface_I2C
#define _bdd_A2bDeviceInterface_MAX bdd_A2bDeviceInterface_SPI
#define _bdd_A2bDeviceInterface_ARRAYSIZE ((bdd_A2bDeviceInterface)(bdd_A2bDeviceInterface_SPI+1))

#define _bdd_A2bCableType_MIN bdd_A2bCableType_UTP
#define _bdd_A2bCableType_MAX bdd_A2bCableType_RJ45
#define _bdd_A2bCableType_ARRAYSIZE ((bdd_A2bCableType)(bdd_A2bCableType_RJ45+1))


















#define bdd_NodeSettings_bLocalPwrd_ENUMTYPE bdd_nodePowerMode
#define bdd_NodeSettings_eHighPwrSwitchCfg_ENUMTYPE bdd_highPwrSwitchCfg

#define bdd_Node_nodeType_ENUMTYPE bdd_NodeType

#define bdd_NetworkPolicy_discoveryMode_ENUMTYPE bdd_DiscoveryMode
#define bdd_NetworkPolicy_cfgMethod_ENUMTYPE bdd_ConfigMethod
#define bdd_NetworkPolicy_cfgPriority_ENUMTYPE bdd_ConfigPriority
#define bdd_NetworkPolicy_cfgErrPolicy_ENUMTYPE bdd_ConfigErrPolicy
#define bdd_NetworkPolicy_eA2bDeviceInterface_ENUMTYPE bdd_A2bDeviceInterface
#define bdd_NetworkPolicy_eCableType_ENUMTYPE bdd_A2bCableType



/* Initializer values for message structs */
#define bdd_MetaData_init_default                {0, 0, false, "", false, "", false, "", false, 1u}
#define bdd_CustomNodeIdSettings_init_default    {false, 0, false, 0, false, 0, false, 0, false, "", false, 0, false, 0, false, 0, false, 0, 0, {0, 0, 0, 0, 0, 0, 0, 0}, false, 0, false, 0}
#define bdd_NodeDescriptor_init_default          {0, 0, 0, false, bdd_CustomNodeIdSettings_init_default, false, 0}
#define bdd_CtrlRegs_init_default                {false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0}
#define bdd_VmtrRegs_init_default                {false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0}
#define bdd_I2sCrossbarRegs_init_default         {false, 0, 0, {0, 0, 0, 0, 0, 0, 0, 0}, false, 0, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}}
#define bdd_PwmRegs_init_default                 {false, 0, false, 0, false, 0, false, 0, false, 0, 0, {0, 0, 0, 0, 0, 0}, false, 0, 0, {0, 0}}
#define bdd_SpiRegs_init_default                 {false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0}
#define bdd_DataTunnelRegs_init_default          {false, 0, false, 0, false, 0, false, 0}
#define bdd_IntRegs_init_default                 {false, 0, false, 0, false, 0, false, 0}
#define bdd_TuningRegs_init_default              {false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0}
#define bdd_I2cI2sRegs_init_default              {false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0}
#define bdd_PinIoRegs_init_default               {false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0}
#define bdd_DataSlotEnhancementRegs_init_default {false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0}
#define bdd_GpioDRegs_init_default               {false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0}
#define bdd_MailboxRegs_init_default             {false, 0, false, 0}
#define bdd_DebugRegs_init_default               {false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0}
#define bdd_NodeSettings_init_default            {false, _bdd_nodePowerMode_MIN, false, _bdd_highPwrSwitchCfg_MIN}
#define bdd_Node_init_default                    {_bdd_NodeType_MIN, bdd_CtrlRegs_init_default, false, bdd_IntRegs_init_default, false, bdd_TuningRegs_init_default, bdd_I2cI2sRegs_init_default, bdd_PinIoRegs_init_default, 0, 0, bdd_NodeDescriptor_init_default, 0, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, 0, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, false, bdd_DataSlotEnhancementRegs_init_default, false, bdd_GpioDRegs_init_default, false, bdd_MailboxRegs_init_default, false, bdd_I2sCrossbarRegs_init_default, false, bdd_PwmRegs_init_default, false, bdd_SpiRegs_init_default, false, bdd_DataTunnelRegs_init_default, false, bdd_VmtrRegs_init_default, false, bdd_DebugRegs_init_default, false, bdd_NodeSettings_init_default}
#define bdd_NetworkPolicy_init_default           {_bdd_DiscoveryMode_MIN, _bdd_ConfigMethod_MIN, _bdd_ConfigPriority_MIN, _bdd_ConfigErrPolicy_MIN, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, _bdd_A2bDeviceInterface_MIN, false, _bdd_A2bCableType_MIN}
#define bdd_Network_init_default                 {bdd_MetaData_init_default, 0, bdd_NetworkPolicy_init_default, 0, {bdd_Node_init_default, bdd_Node_init_default, bdd_Node_init_default, bdd_Node_init_default, bdd_Node_init_default, bdd_Node_init_default, bdd_Node_init_default, bdd_Node_init_default, bdd_Node_init_default, bdd_Node_init_default, bdd_Node_init_default, bdd_Node_init_default, bdd_Node_init_default, bdd_Node_init_default, bdd_Node_init_default, bdd_Node_init_default, bdd_Node_init_default}, 0}
#define bdd_MetaData_init_zero                   {0, 0, false, "", false, "", false, "", false, 0}
#define bdd_CustomNodeIdSettings_init_zero       {false, 0, false, 0, false, 0, false, 0, false, "", false, 0, false, 0, false, 0, false, 0, 0, {0, 0, 0, 0, 0, 0, 0, 0}, false, 0, false, 0}
#define bdd_NodeDescriptor_init_zero             {0, 0, 0, false, bdd_CustomNodeIdSettings_init_zero, false, 0}
#define bdd_CtrlRegs_init_zero                   {false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0}
#define bdd_VmtrRegs_init_zero                   {false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0}
#define bdd_I2sCrossbarRegs_init_zero            {false, 0, 0, {0, 0, 0, 0, 0, 0, 0, 0}, false, 0, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}}
#define bdd_PwmRegs_init_zero                    {false, 0, false, 0, false, 0, false, 0, false, 0, 0, {0, 0, 0, 0, 0, 0}, false, 0, 0, {0, 0}}
#define bdd_SpiRegs_init_zero                    {false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0}
#define bdd_DataTunnelRegs_init_zero             {false, 0, false, 0, false, 0, false, 0}
#define bdd_IntRegs_init_zero                    {false, 0, false, 0, false, 0, false, 0}
#define bdd_TuningRegs_init_zero                 {false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0}
#define bdd_I2cI2sRegs_init_zero                 {false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0}
#define bdd_PinIoRegs_init_zero                  {false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0}
#define bdd_DataSlotEnhancementRegs_init_zero    {false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0}
#define bdd_GpioDRegs_init_zero                  {false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0}
#define bdd_MailboxRegs_init_zero                {false, 0, false, 0}
#define bdd_DebugRegs_init_zero                  {false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0}
#define bdd_NodeSettings_init_zero               {false, _bdd_nodePowerMode_MIN, false, _bdd_highPwrSwitchCfg_MIN}
#define bdd_Node_init_zero                       {_bdd_NodeType_MIN, bdd_CtrlRegs_init_zero, false, bdd_IntRegs_init_zero, false, bdd_TuningRegs_init_zero, bdd_I2cI2sRegs_init_zero, bdd_PinIoRegs_init_zero, 0, 0, bdd_NodeDescriptor_init_zero, 0, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, 0, 0, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}, false, bdd_DataSlotEnhancementRegs_init_zero, false, bdd_GpioDRegs_init_zero, false, bdd_MailboxRegs_init_zero, false, bdd_I2sCrossbarRegs_init_zero, false, bdd_PwmRegs_init_zero, false, bdd_SpiRegs_init_zero, false, bdd_DataTunnelRegs_init_zero, false, bdd_VmtrRegs_init_zero, false, bdd_DebugRegs_init_zero, false, bdd_NodeSettings_init_zero}
#define bdd_NetworkPolicy_init_zero              {_bdd_DiscoveryMode_MIN, _bdd_ConfigMethod_MIN, _bdd_ConfigPriority_MIN, _bdd_ConfigErrPolicy_MIN, false, 0, false, 0, false, 0, false, 0, false, 0, false, 0, false, _bdd_A2bDeviceInterface_MIN, false, _bdd_A2bCableType_MIN}
#define bdd_Network_init_zero                    {bdd_MetaData_init_zero, 0, bdd_NetworkPolicy_init_zero, 0, {bdd_Node_init_zero, bdd_Node_init_zero, bdd_Node_init_zero, bdd_Node_init_zero, bdd_Node_init_zero, bdd_Node_init_zero, bdd_Node_init_zero, bdd_Node_init_zero, bdd_Node_init_zero, bdd_Node_init_zero, bdd_Node_init_zero, bdd_Node_init_zero, bdd_Node_init_zero, bdd_Node_init_zero, bdd_Node_init_zero, bdd_Node_init_zero, bdd_Node_init_zero}, 0}

/* Field tags (for use in manual encoding/decoding) */
#define bdd_MetaData_date_tag                    1
#define bdd_MetaData_version_tag                 2
#define bdd_MetaData_author_tag                  3
#define bdd_MetaData_organization_tag            4
#define bdd_MetaData_company_tag                 5
#define bdd_MetaData_bddVersion_tag              6
#define bdd_CustomNodeIdSettings_bCustomNodeIdAuth_tag 1
#define bdd_CustomNodeIdSettings_bReadFrmMemory_tag 2
#define bdd_CustomNodeIdSettings_bReadFrmCommCh_tag 3
#define bdd_CustomNodeIdSettings_nDeviceAddr_tag 4
#define bdd_CustomNodeIdSettings_nNodeId_tag     5
#define bdd_CustomNodeIdSettings_nNodeIdLength_tag 6
#define bdd_CustomNodeIdSettings_nReadMemAddrWidth_tag 7
#define bdd_CustomNodeIdSettings_nReadMemAddr_tag 8
#define bdd_CustomNodeIdSettings_bReadGpioPins_tag 9
#define bdd_CustomNodeIdSettings_aGpio_tag       10
#define bdd_CustomNodeIdSettings_nTimeOut_tag    11
#define bdd_CustomNodeIdSettings_nRetryCnt_tag   12
#define bdd_NodeDescriptor_vendor_tag            1
#define bdd_NodeDescriptor_product_tag           2
#define bdd_NodeDescriptor_version_tag           3
#define bdd_NodeDescriptor_oCustomNodeIdSettings_tag 4
#define bdd_NodeDescriptor_btwoStepDisc_tag      5
#define bdd_CtrlRegs_bcdnslots_tag               1
#define bdd_CtrlRegs_ldnslots_tag                2
#define bdd_CtrlRegs_lupslots_tag                3
#define bdd_CtrlRegs_dnslots_tag                 4
#define bdd_CtrlRegs_upslots_tag                 5
#define bdd_CtrlRegs_respcycs_tag                6
#define bdd_CtrlRegs_slotfmt_tag                 7
#define bdd_CtrlRegs_suscfg_tag                  8
#define bdd_CtrlRegs_datctl_tag                  9
#define bdd_CtrlRegs_control_tag                 10
#define bdd_CtrlRegs_swctl_tag                   11
#define bdd_CtrlRegs_swctl2_tag                  12
#define bdd_CtrlRegs_swctl3_tag                  13
#define bdd_CtrlRegs_swctl4_tag                  14
#define bdd_CtrlRegs_swctl5_tag                  15
#define bdd_CtrlRegs_swctl6_tag                  16
#define bdd_VmtrRegs_vmtr_ven_tag                1
#define bdd_VmtrRegs_vmtr_inten_tag              2
#define bdd_VmtrRegs_vmtr_mxstat_tag             3
#define bdd_VmtrRegs_vmtr_mnstat_tag             4
#define bdd_VmtrRegs_vmtr_vmax0_tag              5
#define bdd_VmtrRegs_vmtr_vmin0_tag              6
#define bdd_VmtrRegs_vmtr_vmax1_tag              7
#define bdd_VmtrRegs_vmtr_vmin1_tag              8
#define bdd_VmtrRegs_vmtr_vmax2_tag              9
#define bdd_VmtrRegs_vmtr_vmin2_tag              10
#define bdd_VmtrRegs_vmtr_vmax3_tag              11
#define bdd_VmtrRegs_vmtr_vmin3_tag              12
#define bdd_VmtrRegs_vmtr_vmax4_tag              13
#define bdd_VmtrRegs_vmtr_vmin4_tag              14
#define bdd_VmtrRegs_vmtr_vmax5_tag              15
#define bdd_VmtrRegs_vmtr_vmin5_tag              16
#define bdd_VmtrRegs_vmtr_vmax6_tag              17
#define bdd_VmtrRegs_vmtr_vmin6_tag              18
#define bdd_I2sCrossbarRegs_has_rxmask_tag       1
#define bdd_I2sCrossbarRegs_rxmask_tag           2
#define bdd_I2sCrossbarRegs_has_txcrossbar_tag   3
#define bdd_I2sCrossbarRegs_txcrossbar_tag       4
#define bdd_PwmRegs_pwmcfg_tag                   1
#define bdd_PwmRegs_pwmfreq_tag                  2
#define bdd_PwmRegs_pwmblink1_tag                3
#define bdd_PwmRegs_pwmblink2_tag                4
#define bdd_PwmRegs_has_pwmval_tag               5
#define bdd_PwmRegs_pwmval_tag                   6
#define bdd_PwmRegs_has_pwmoe_tag                7
#define bdd_PwmRegs_pwmoe_tag                    8
#define bdd_SpiRegs_spicfg_tag                   1
#define bdd_SpiRegs_spickdiv_tag                 2
#define bdd_SpiRegs_spifdsize_tag                3
#define bdd_SpiRegs_spifdtarg_tag                4
#define bdd_SpiRegs_spipicfg_tag                 5
#define bdd_SpiRegs_spiint_tag                   6
#define bdd_SpiRegs_spimsk_tag                   7
#define bdd_DataTunnelRegs_dtcfg_tag             1
#define bdd_DataTunnelRegs_dtslots_tag           2
#define bdd_DataTunnelRegs_dtndnoffs_tag         3
#define bdd_DataTunnelRegs_dtnupoffs_tag         4
#define bdd_IntRegs_intmsk0_tag                  1
#define bdd_IntRegs_intmsk1_tag                  2
#define bdd_IntRegs_intmsk2_tag                  3
#define bdd_IntRegs_becctl_tag                   4
#define bdd_TuningRegs_vregctl_tag               1
#define bdd_TuningRegs_txactl_tag                2
#define bdd_TuningRegs_rxactl_tag                3
#define bdd_TuningRegs_txbctl_tag                4
#define bdd_TuningRegs_rxbctl_tag                5
#define bdd_TuningRegs_txctl_tag                 6
#define bdd_TuningRegs_rxctl_tag                 7
#define bdd_I2cI2sRegs_i2ccfg_tag                1
#define bdd_I2cI2sRegs_pllctl_tag                2
#define bdd_I2cI2sRegs_i2sgcfg_tag               3
#define bdd_I2cI2sRegs_i2scfg_tag                4
#define bdd_I2cI2sRegs_i2srate_tag               5
#define bdd_I2cI2sRegs_i2stxoffset_tag           6
#define bdd_I2cI2sRegs_i2srxoffset_tag           7
#define bdd_I2cI2sRegs_syncoffset_tag            8
#define bdd_I2cI2sRegs_pdmctl_tag                9
#define bdd_I2cI2sRegs_errmgmt_tag               10
#define bdd_I2cI2sRegs_i2srrate_tag              11
#define bdd_I2cI2sRegs_i2srrctl_tag              12
#define bdd_I2cI2sRegs_i2srrsoffs_tag            13
#define bdd_I2cI2sRegs_pdmctl2_tag               14
#define bdd_I2cI2sRegs_i2stest_tag               15
#define bdd_PinIoRegs_clkcfg_tag                 1
#define bdd_PinIoRegs_gpiooen_tag                3
#define bdd_PinIoRegs_gpioien_tag                4
#define bdd_PinIoRegs_pinten_tag                 5
#define bdd_PinIoRegs_pintinv_tag                6
#define bdd_PinIoRegs_pincfg_tag                 7
#define bdd_PinIoRegs_gpiodat_tag                8
#define bdd_PinIoRegs_clk1cfg_tag                9
#define bdd_PinIoRegs_clk2cfg_tag                10
#define bdd_DataSlotEnhancementRegs_upmask0_tag  1
#define bdd_DataSlotEnhancementRegs_upmask1_tag  2
#define bdd_DataSlotEnhancementRegs_upmask2_tag  3
#define bdd_DataSlotEnhancementRegs_upmask3_tag  4
#define bdd_DataSlotEnhancementRegs_upoffset_tag 5
#define bdd_DataSlotEnhancementRegs_dnmask0_tag  6
#define bdd_DataSlotEnhancementRegs_dnmask1_tag  7
#define bdd_DataSlotEnhancementRegs_dnmask2_tag  8
#define bdd_DataSlotEnhancementRegs_dnmask3_tag  9
#define bdd_DataSlotEnhancementRegs_dnoffset_tag 10
#define bdd_GpioDRegs_gpioden_tag                1
#define bdd_GpioDRegs_gpiod0msk_tag              2
#define bdd_GpioDRegs_gpiod1msk_tag              3
#define bdd_GpioDRegs_gpiod2msk_tag              4
#define bdd_GpioDRegs_gpiod3msk_tag              5
#define bdd_GpioDRegs_gpiod4msk_tag              6
#define bdd_GpioDRegs_gpiod5msk_tag              7
#define bdd_GpioDRegs_gpiod6msk_tag              8
#define bdd_GpioDRegs_gpiod7msk_tag              9
#define bdd_GpioDRegs_gpioddat_tag               10
#define bdd_GpioDRegs_gpiodinv_tag               11
#define bdd_MailboxRegs_mbox0ctl_tag             1
#define bdd_MailboxRegs_mbox1ctl_tag             2
#define bdd_DebugRegs_debugReg1_tag              1
#define bdd_DebugRegs_debugReg2_tag              2
#define bdd_DebugRegs_debugReg3_tag              3
#define bdd_DebugRegs_debugReg4_tag              4
#define bdd_DebugRegs_debugReg5_tag              5
#define bdd_DebugRegs_debugReg6_tag              6
#define bdd_DebugRegs_debugReg7_tag              7
#define bdd_DebugRegs_debugReg8_tag              8
#define bdd_DebugRegs_debugReg9_tag              9
#define bdd_DebugRegs_debugReg10_tag             10
#define bdd_NodeSettings_bLocalPwrd_tag          1
#define bdd_NodeSettings_eHighPwrSwitchCfg_tag   2
#define bdd_Node_nodeType_tag                    1
#define bdd_Node_ctrlRegs_tag                    2
#define bdd_Node_intRegs_tag                     3
#define bdd_Node_tuningRegs_tag                  4
#define bdd_Node_i2cI2sRegs_tag                  5
#define bdd_Node_pinIoRegs_tag                   6
#define bdd_Node_ignEeprom_tag                   7
#define bdd_Node_verifyNodeDescr_tag             8
#define bdd_Node_nodeDescr_tag                   9
#define bdd_Node_downstreamBcastCnt_tag          10
#define bdd_Node_downstream_tag                  11
#define bdd_Node_upstreamBcastCnt_tag            12
#define bdd_Node_upstream_tag                    13
#define bdd_Node_slotEnh_tag                     14
#define bdd_Node_gpioDist_tag                    15
#define bdd_Node_mbox_tag                        16
#define bdd_Node_i2sCrossbarRegs_tag             17
#define bdd_Node_pwmRegs_tag                     18
#define bdd_Node_spiRegs_tag                     19
#define bdd_Node_dataTunnelRegs_tag              20
#define bdd_Node_vmtrRegs_tag                    21
#define bdd_Node_debugReg_tag                    22
#define bdd_Node_nodeSetting_tag                 23
#define bdd_NetworkPolicy_discoveryMode_tag      1
#define bdd_NetworkPolicy_cfgMethod_tag          2
#define bdd_NetworkPolicy_cfgPriority_tag        3
#define bdd_NetworkPolicy_cfgErrPolicy_tag       4
#define bdd_NetworkPolicy_has_common_SSSettings_tag 5
#define bdd_NetworkPolicy_discoveryStartDelay_tag 6
#define bdd_NetworkPolicy_bOverrideSelfDisc_tag  7
#define bdd_NetworkPolicy_bCrossTalkFixApply_tag 8
#define bdd_NetworkPolicy_nRediscWaitTime_tag    9
#define bdd_NetworkPolicy_bEnablePartialDisc_tag 10
#define bdd_NetworkPolicy_eA2bDeviceInterface_tag 11
#define bdd_NetworkPolicy_eCableType_tag         12
#define bdd_Network_metaData_tag                 1
#define bdd_Network_masterAddr_tag               2
#define bdd_Network_policy_tag                   3
#define bdd_Network_nodes_tag                    4
#define bdd_Network_sampleRate_tag               5

/* Struct field encoding specification for nanopb */
#define bdd_MetaData_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, FIXED32,  date,              1) \
X(a, STATIC,   REQUIRED, FIXED32,  version,           2) \
X(a, STATIC,   OPTIONAL, STRING,   author,            3) \
X(a, STATIC,   OPTIONAL, STRING,   organization,      4) \
X(a, STATIC,   OPTIONAL, STRING,   company,           5) \
X(a, STATIC,   OPTIONAL, UINT32,   bddVersion,        6)
#define bdd_MetaData_CALLBACK NULL
#define bdd_MetaData_DEFAULT (const pb_byte_t*)"\x30\x01\x00"

#define bdd_CustomNodeIdSettings_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UINT32,   bCustomNodeIdAuth,   1) \
X(a, STATIC,   OPTIONAL, UINT32,   bReadFrmMemory,    2) \
X(a, STATIC,   OPTIONAL, UINT32,   bReadFrmCommCh,    3) \
X(a, STATIC,   OPTIONAL, UINT32,   nDeviceAddr,       4) \
X(a, STATIC,   OPTIONAL, STRING,   nNodeId,           5) \
X(a, STATIC,   OPTIONAL, UINT32,   nNodeIdLength,     6) \
X(a, STATIC,   OPTIONAL, UINT32,   nReadMemAddrWidth,   7) \
X(a, STATIC,   OPTIONAL, UINT32,   nReadMemAddr,      8) \
X(a, STATIC,   OPTIONAL, UINT32,   bReadGpioPins,     9) \
X(a, STATIC,   REPEATED, UINT32,   aGpio,            10) \
X(a, STATIC,   OPTIONAL, UINT32,   nTimeOut,         11) \
X(a, STATIC,   OPTIONAL, UINT32,   nRetryCnt,        12)
#define bdd_CustomNodeIdSettings_CALLBACK NULL
#define bdd_CustomNodeIdSettings_DEFAULT NULL

#define bdd_NodeDescriptor_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, UINT32,   vendor,            1) \
X(a, STATIC,   REQUIRED, UINT32,   product,           2) \
X(a, STATIC,   REQUIRED, UINT32,   version,           3) \
X(a, STATIC,   OPTIONAL, MESSAGE,  oCustomNodeIdSettings,   4) \
X(a, STATIC,   OPTIONAL, UINT32,   btwoStepDisc,      5)
#define bdd_NodeDescriptor_CALLBACK NULL
#define bdd_NodeDescriptor_DEFAULT NULL
#define bdd_NodeDescriptor_oCustomNodeIdSettings_MSGTYPE bdd_CustomNodeIdSettings

#define bdd_CtrlRegs_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UINT32,   bcdnslots,         1) \
X(a, STATIC,   OPTIONAL, UINT32,   ldnslots,          2) \
X(a, STATIC,   OPTIONAL, UINT32,   lupslots,          3) \
X(a, STATIC,   OPTIONAL, UINT32,   dnslots,           4) \
X(a, STATIC,   OPTIONAL, UINT32,   upslots,           5) \
X(a, STATIC,   OPTIONAL, UINT32,   respcycs,          6) \
X(a, STATIC,   OPTIONAL, UINT32,   slotfmt,           7) \
X(a, STATIC,   OPTIONAL, UINT32,   suscfg,            8) \
X(a, STATIC,   OPTIONAL, UINT32,   datctl,            9) \
X(a, STATIC,   OPTIONAL, UINT32,   control,          10) \
X(a, STATIC,   OPTIONAL, UINT32,   swctl,            11) \
X(a, STATIC,   OPTIONAL, UINT32,   swctl2,           12) \
X(a, STATIC,   OPTIONAL, UINT32,   swctl3,           13) \
X(a, STATIC,   OPTIONAL, UINT32,   swctl4,           14) \
X(a, STATIC,   OPTIONAL, UINT32,   swctl5,           15) \
X(a, STATIC,   OPTIONAL, UINT32,   swctl6,           16)
#define bdd_CtrlRegs_CALLBACK NULL
#define bdd_CtrlRegs_DEFAULT NULL

#define bdd_VmtrRegs_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UINT32,   vmtr_ven,          1) \
X(a, STATIC,   OPTIONAL, UINT32,   vmtr_inten,        2) \
X(a, STATIC,   OPTIONAL, UINT32,   vmtr_mxstat,       3) \
X(a, STATIC,   OPTIONAL, UINT32,   vmtr_mnstat,       4) \
X(a, STATIC,   OPTIONAL, UINT32,   vmtr_vmax0,        5) \
X(a, STATIC,   OPTIONAL, UINT32,   vmtr_vmin0,        6) \
X(a, STATIC,   OPTIONAL, UINT32,   vmtr_vmax1,        7) \
X(a, STATIC,   OPTIONAL, UINT32,   vmtr_vmin1,        8) \
X(a, STATIC,   OPTIONAL, UINT32,   vmtr_vmax2,        9) \
X(a, STATIC,   OPTIONAL, UINT32,   vmtr_vmin2,       10) \
X(a, STATIC,   OPTIONAL, UINT32,   vmtr_vmax3,       11) \
X(a, STATIC,   OPTIONAL, UINT32,   vmtr_vmin3,       12) \
X(a, STATIC,   OPTIONAL, UINT32,   vmtr_vmax4,       13) \
X(a, STATIC,   OPTIONAL, UINT32,   vmtr_vmin4,       14) \
X(a, STATIC,   OPTIONAL, UINT32,   vmtr_vmax5,       15) \
X(a, STATIC,   OPTIONAL, UINT32,   vmtr_vmin5,       16) \
X(a, STATIC,   OPTIONAL, UINT32,   vmtr_vmax6,       17) \
X(a, STATIC,   OPTIONAL, UINT32,   vmtr_vmin6,       18)
#define bdd_VmtrRegs_CALLBACK NULL
#define bdd_VmtrRegs_DEFAULT NULL

#define bdd_I2sCrossbarRegs_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, BOOL,     has_rxmask,        1) \
X(a, STATIC,   REPEATED, UINT32,   rxmask,            2) \
X(a, STATIC,   OPTIONAL, BOOL,     has_txcrossbar,    3) \
X(a, STATIC,   REPEATED, UINT32,   txcrossbar,        4)
#define bdd_I2sCrossbarRegs_CALLBACK NULL
#define bdd_I2sCrossbarRegs_DEFAULT NULL

#define bdd_PwmRegs_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UINT32,   pwmcfg,            1) \
X(a, STATIC,   OPTIONAL, UINT32,   pwmfreq,           2) \
X(a, STATIC,   OPTIONAL, UINT32,   pwmblink1,         3) \
X(a, STATIC,   OPTIONAL, UINT32,   pwmblink2,         4) \
X(a, STATIC,   OPTIONAL, BOOL,     has_pwmval,        5) \
X(a, STATIC,   REPEATED, UINT32,   pwmval,            6) \
X(a, STATIC,   OPTIONAL, BOOL,     has_pwmoe,         7) \
X(a, STATIC,   REPEATED, UINT32,   pwmoe,             8)
#define bdd_PwmRegs_CALLBACK NULL
#define bdd_PwmRegs_DEFAULT NULL

#define bdd_SpiRegs_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UINT32,   spicfg,            1) \
X(a, STATIC,   OPTIONAL, UINT32,   spickdiv,          2) \
X(a, STATIC,   OPTIONAL, UINT32,   spifdsize,         3) \
X(a, STATIC,   OPTIONAL, UINT32,   spifdtarg,         4) \
X(a, STATIC,   OPTIONAL, UINT32,   spipicfg,          5) \
X(a, STATIC,   OPTIONAL, UINT32,   spiint,            6) \
X(a, STATIC,   OPTIONAL, UINT32,   spimsk,            7)
#define bdd_SpiRegs_CALLBACK NULL
#define bdd_SpiRegs_DEFAULT NULL

#define bdd_DataTunnelRegs_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UINT32,   dtcfg,             1) \
X(a, STATIC,   OPTIONAL, UINT32,   dtslots,           2) \
X(a, STATIC,   OPTIONAL, UINT32,   dtndnoffs,         3) \
X(a, STATIC,   OPTIONAL, UINT32,   dtnupoffs,         4)
#define bdd_DataTunnelRegs_CALLBACK NULL
#define bdd_DataTunnelRegs_DEFAULT NULL

#define bdd_IntRegs_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UINT32,   intmsk0,           1) \
X(a, STATIC,   OPTIONAL, UINT32,   intmsk1,           2) \
X(a, STATIC,   OPTIONAL, UINT32,   intmsk2,           3) \
X(a, STATIC,   OPTIONAL, UINT32,   becctl,            4)
#define bdd_IntRegs_CALLBACK NULL
#define bdd_IntRegs_DEFAULT NULL

#define bdd_TuningRegs_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UINT32,   vregctl,           1) \
X(a, STATIC,   OPTIONAL, UINT32,   txactl,            2) \
X(a, STATIC,   OPTIONAL, UINT32,   rxactl,            3) \
X(a, STATIC,   OPTIONAL, UINT32,   txbctl,            4) \
X(a, STATIC,   OPTIONAL, UINT32,   rxbctl,            5) \
X(a, STATIC,   OPTIONAL, UINT32,   txctl,             6) \
X(a, STATIC,   OPTIONAL, UINT32,   rxctl,             7)
#define bdd_TuningRegs_CALLBACK NULL
#define bdd_TuningRegs_DEFAULT NULL

#define bdd_I2cI2sRegs_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UINT32,   i2ccfg,            1) \
X(a, STATIC,   OPTIONAL, UINT32,   pllctl,            2) \
X(a, STATIC,   OPTIONAL, UINT32,   i2sgcfg,           3) \
X(a, STATIC,   OPTIONAL, UINT32,   i2scfg,            4) \
X(a, STATIC,   OPTIONAL, UINT32,   i2srate,           5) \
X(a, STATIC,   OPTIONAL, UINT32,   i2stxoffset,       6) \
X(a, STATIC,   OPTIONAL, UINT32,   i2srxoffset,       7) \
X(a, STATIC,   OPTIONAL, UINT32,   syncoffset,        8) \
X(a, STATIC,   OPTIONAL, UINT32,   pdmctl,            9) \
X(a, STATIC,   OPTIONAL, UINT32,   errmgmt,          10) \
X(a, STATIC,   OPTIONAL, UINT32,   i2srrate,         11) \
X(a, STATIC,   OPTIONAL, UINT32,   i2srrctl,         12) \
X(a, STATIC,   OPTIONAL, UINT32,   i2srrsoffs,       13) \
X(a, STATIC,   OPTIONAL, UINT32,   pdmctl2,          14) \
X(a, STATIC,   OPTIONAL, UINT32,   i2stest,          15)
#define bdd_I2cI2sRegs_CALLBACK NULL
#define bdd_I2cI2sRegs_DEFAULT NULL

#define bdd_PinIoRegs_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UINT32,   clkcfg,            1) \
X(a, STATIC,   OPTIONAL, UINT32,   gpiooen,           3) \
X(a, STATIC,   OPTIONAL, UINT32,   gpioien,           4) \
X(a, STATIC,   OPTIONAL, UINT32,   pinten,            5) \
X(a, STATIC,   OPTIONAL, UINT32,   pintinv,           6) \
X(a, STATIC,   OPTIONAL, UINT32,   pincfg,            7) \
X(a, STATIC,   OPTIONAL, UINT32,   gpiodat,           8) \
X(a, STATIC,   OPTIONAL, UINT32,   clk1cfg,           9) \
X(a, STATIC,   OPTIONAL, UINT32,   clk2cfg,          10)
#define bdd_PinIoRegs_CALLBACK NULL
#define bdd_PinIoRegs_DEFAULT NULL

#define bdd_DataSlotEnhancementRegs_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UINT32,   upmask0,           1) \
X(a, STATIC,   OPTIONAL, UINT32,   upmask1,           2) \
X(a, STATIC,   OPTIONAL, UINT32,   upmask2,           3) \
X(a, STATIC,   OPTIONAL, UINT32,   upmask3,           4) \
X(a, STATIC,   OPTIONAL, UINT32,   upoffset,          5) \
X(a, STATIC,   OPTIONAL, UINT32,   dnmask0,           6) \
X(a, STATIC,   OPTIONAL, UINT32,   dnmask1,           7) \
X(a, STATIC,   OPTIONAL, UINT32,   dnmask2,           8) \
X(a, STATIC,   OPTIONAL, UINT32,   dnmask3,           9) \
X(a, STATIC,   OPTIONAL, UINT32,   dnoffset,         10)
#define bdd_DataSlotEnhancementRegs_CALLBACK NULL
#define bdd_DataSlotEnhancementRegs_DEFAULT NULL

#define bdd_GpioDRegs_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UINT32,   gpioden,           1) \
X(a, STATIC,   OPTIONAL, UINT32,   gpiod0msk,         2) \
X(a, STATIC,   OPTIONAL, UINT32,   gpiod1msk,         3) \
X(a, STATIC,   OPTIONAL, UINT32,   gpiod2msk,         4) \
X(a, STATIC,   OPTIONAL, UINT32,   gpiod3msk,         5) \
X(a, STATIC,   OPTIONAL, UINT32,   gpiod4msk,         6) \
X(a, STATIC,   OPTIONAL, UINT32,   gpiod5msk,         7) \
X(a, STATIC,   OPTIONAL, UINT32,   gpiod6msk,         8) \
X(a, STATIC,   OPTIONAL, UINT32,   gpiod7msk,         9) \
X(a, STATIC,   OPTIONAL, UINT32,   gpioddat,         10) \
X(a, STATIC,   OPTIONAL, UINT32,   gpiodinv,         11)
#define bdd_GpioDRegs_CALLBACK NULL
#define bdd_GpioDRegs_DEFAULT NULL

#define bdd_MailboxRegs_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UINT32,   mbox0ctl,          1) \
X(a, STATIC,   OPTIONAL, UINT32,   mbox1ctl,          2)
#define bdd_MailboxRegs_CALLBACK NULL
#define bdd_MailboxRegs_DEFAULT NULL

#define bdd_DebugRegs_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UINT32,   debugReg1,         1) \
X(a, STATIC,   OPTIONAL, UINT32,   debugReg2,         2) \
X(a, STATIC,   OPTIONAL, UINT32,   debugReg3,         3) \
X(a, STATIC,   OPTIONAL, UINT32,   debugReg4,         4) \
X(a, STATIC,   OPTIONAL, UINT32,   debugReg5,         5) \
X(a, STATIC,   OPTIONAL, UINT32,   debugReg6,         6) \
X(a, STATIC,   OPTIONAL, UINT32,   debugReg7,         7) \
X(a, STATIC,   OPTIONAL, UINT32,   debugReg8,         8) \
X(a, STATIC,   OPTIONAL, UINT32,   debugReg9,         9) \
X(a, STATIC,   OPTIONAL, UINT32,   debugReg10,       10)
#define bdd_DebugRegs_CALLBACK NULL
#define bdd_DebugRegs_DEFAULT NULL

#define bdd_NodeSettings_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UENUM,    bLocalPwrd,        1) \
X(a, STATIC,   OPTIONAL, UENUM,    eHighPwrSwitchCfg,   2)
#define bdd_NodeSettings_CALLBACK NULL
#define bdd_NodeSettings_DEFAULT NULL

#define bdd_Node_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, UENUM,    nodeType,          1) \
X(a, STATIC,   REQUIRED, MESSAGE,  ctrlRegs,          2) \
X(a, STATIC,   OPTIONAL, MESSAGE,  intRegs,           3) \
X(a, STATIC,   OPTIONAL, MESSAGE,  tuningRegs,        4) \
X(a, STATIC,   REQUIRED, MESSAGE,  i2cI2sRegs,        5) \
X(a, STATIC,   REQUIRED, MESSAGE,  pinIoRegs,         6) \
X(a, STATIC,   REQUIRED, BOOL,     ignEeprom,         7) \
X(a, STATIC,   REQUIRED, BOOL,     verifyNodeDescr,   8) \
X(a, STATIC,   REQUIRED, MESSAGE,  nodeDescr,         9) \
X(a, STATIC,   REQUIRED, UINT32,   downstreamBcastCnt,  10) \
X(a, STATIC,   REPEATED, UINT32,   downstream,       11) \
X(a, STATIC,   REQUIRED, UINT32,   upstreamBcastCnt,  12) \
X(a, STATIC,   REPEATED, UINT32,   upstream,         13) \
X(a, STATIC,   OPTIONAL, MESSAGE,  slotEnh,          14) \
X(a, STATIC,   OPTIONAL, MESSAGE,  gpioDist,         15) \
X(a, STATIC,   OPTIONAL, MESSAGE,  mbox,             16) \
X(a, STATIC,   OPTIONAL, MESSAGE,  i2sCrossbarRegs,  17) \
X(a, STATIC,   OPTIONAL, MESSAGE,  pwmRegs,          18) \
X(a, STATIC,   OPTIONAL, MESSAGE,  spiRegs,          19) \
X(a, STATIC,   OPTIONAL, MESSAGE,  dataTunnelRegs,   20) \
X(a, STATIC,   OPTIONAL, MESSAGE,  vmtrRegs,         21) \
X(a, STATIC,   OPTIONAL, MESSAGE,  debugReg,         22) \
X(a, STATIC,   OPTIONAL, MESSAGE,  nodeSetting,      23)
#define bdd_Node_CALLBACK NULL
#define bdd_Node_DEFAULT NULL
#define bdd_Node_ctrlRegs_MSGTYPE bdd_CtrlRegs
#define bdd_Node_intRegs_MSGTYPE bdd_IntRegs
#define bdd_Node_tuningRegs_MSGTYPE bdd_TuningRegs
#define bdd_Node_i2cI2sRegs_MSGTYPE bdd_I2cI2sRegs
#define bdd_Node_pinIoRegs_MSGTYPE bdd_PinIoRegs
#define bdd_Node_nodeDescr_MSGTYPE bdd_NodeDescriptor
#define bdd_Node_slotEnh_MSGTYPE bdd_DataSlotEnhancementRegs
#define bdd_Node_gpioDist_MSGTYPE bdd_GpioDRegs
#define bdd_Node_mbox_MSGTYPE bdd_MailboxRegs
#define bdd_Node_i2sCrossbarRegs_MSGTYPE bdd_I2sCrossbarRegs
#define bdd_Node_pwmRegs_MSGTYPE bdd_PwmRegs
#define bdd_Node_spiRegs_MSGTYPE bdd_SpiRegs
#define bdd_Node_dataTunnelRegs_MSGTYPE bdd_DataTunnelRegs
#define bdd_Node_vmtrRegs_MSGTYPE bdd_VmtrRegs
#define bdd_Node_debugReg_MSGTYPE bdd_DebugRegs
#define bdd_Node_nodeSetting_MSGTYPE bdd_NodeSettings

#define bdd_NetworkPolicy_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, UENUM,    discoveryMode,     1) \
X(a, STATIC,   REQUIRED, UENUM,    cfgMethod,         2) \
X(a, STATIC,   REQUIRED, UENUM,    cfgPriority,       3) \
X(a, STATIC,   REQUIRED, UENUM,    cfgErrPolicy,      4) \
X(a, STATIC,   OPTIONAL, BOOL,     has_common_SSSettings,   5) \
X(a, STATIC,   OPTIONAL, UINT32,   discoveryStartDelay,   6) \
X(a, STATIC,   OPTIONAL, BOOL,     bOverrideSelfDisc,   7) \
X(a, STATIC,   OPTIONAL, BOOL,     bCrossTalkFixApply,   8) \
X(a, STATIC,   OPTIONAL, UINT32,   nRediscWaitTime,   9) \
X(a, STATIC,   OPTIONAL, BOOL,     bEnablePartialDisc,  10) \
X(a, STATIC,   OPTIONAL, UENUM,    eA2bDeviceInterface,  11) \
X(a, STATIC,   OPTIONAL, UENUM,    eCableType,       12)
#define bdd_NetworkPolicy_CALLBACK NULL
#define bdd_NetworkPolicy_DEFAULT NULL

#define bdd_Network_FIELDLIST(X, a) \
X(a, STATIC,   REQUIRED, MESSAGE,  metaData,          1) \
X(a, STATIC,   REQUIRED, UINT32,   masterAddr,        2) \
X(a, STATIC,   REQUIRED, MESSAGE,  policy,            3) \
X(a, STATIC,   REPEATED, MESSAGE,  nodes,             4) \
X(a, STATIC,   REQUIRED, UINT32,   sampleRate,        5)
#define bdd_Network_CALLBACK NULL
#define bdd_Network_DEFAULT NULL
#define bdd_Network_metaData_MSGTYPE bdd_MetaData
#define bdd_Network_policy_MSGTYPE bdd_NetworkPolicy
#define bdd_Network_nodes_MSGTYPE bdd_Node

extern const pb_msgdesc_t bdd_MetaData_msg;
extern const pb_msgdesc_t bdd_CustomNodeIdSettings_msg;
extern const pb_msgdesc_t bdd_NodeDescriptor_msg;
extern const pb_msgdesc_t bdd_CtrlRegs_msg;
extern const pb_msgdesc_t bdd_VmtrRegs_msg;
extern const pb_msgdesc_t bdd_I2sCrossbarRegs_msg;
extern const pb_msgdesc_t bdd_PwmRegs_msg;
extern const pb_msgdesc_t bdd_SpiRegs_msg;
extern const pb_msgdesc_t bdd_DataTunnelRegs_msg;
extern const pb_msgdesc_t bdd_IntRegs_msg;
extern const pb_msgdesc_t bdd_TuningRegs_msg;
extern const pb_msgdesc_t bdd_I2cI2sRegs_msg;
extern const pb_msgdesc_t bdd_PinIoRegs_msg;
extern const pb_msgdesc_t bdd_DataSlotEnhancementRegs_msg;
extern const pb_msgdesc_t bdd_GpioDRegs_msg;
extern const pb_msgdesc_t bdd_MailboxRegs_msg;
extern const pb_msgdesc_t bdd_DebugRegs_msg;
extern const pb_msgdesc_t bdd_NodeSettings_msg;
extern const pb_msgdesc_t bdd_Node_msg;
extern const pb_msgdesc_t bdd_NetworkPolicy_msg;
extern const pb_msgdesc_t bdd_Network_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define bdd_MetaData_fields &bdd_MetaData_msg
#define bdd_CustomNodeIdSettings_fields &bdd_CustomNodeIdSettings_msg
#define bdd_NodeDescriptor_fields &bdd_NodeDescriptor_msg
#define bdd_CtrlRegs_fields &bdd_CtrlRegs_msg
#define bdd_VmtrRegs_fields &bdd_VmtrRegs_msg
#define bdd_I2sCrossbarRegs_fields &bdd_I2sCrossbarRegs_msg
#define bdd_PwmRegs_fields &bdd_PwmRegs_msg
#define bdd_SpiRegs_fields &bdd_SpiRegs_msg
#define bdd_DataTunnelRegs_fields &bdd_DataTunnelRegs_msg
#define bdd_IntRegs_fields &bdd_IntRegs_msg
#define bdd_TuningRegs_fields &bdd_TuningRegs_msg
#define bdd_I2cI2sRegs_fields &bdd_I2cI2sRegs_msg
#define bdd_PinIoRegs_fields &bdd_PinIoRegs_msg
#define bdd_DataSlotEnhancementRegs_fields &bdd_DataSlotEnhancementRegs_msg
#define bdd_GpioDRegs_fields &bdd_GpioDRegs_msg
#define bdd_MailboxRegs_fields &bdd_MailboxRegs_msg
#define bdd_DebugRegs_fields &bdd_DebugRegs_msg
#define bdd_NodeSettings_fields &bdd_NodeSettings_msg
#define bdd_Node_fields &bdd_Node_msg
#define bdd_NetworkPolicy_fields &bdd_NetworkPolicy_msg
#define bdd_Network_fields &bdd_Network_msg

/* Maximum encoded size of messages (where known) */
#define BDD_BDD_PB_H_MAX_SIZE                    bdd_Network_size
#define bdd_CtrlRegs_size                        97
#define bdd_CustomNodeIdSettings_size            173
#define bdd_DataSlotEnhancementRegs_size         60
#define bdd_DataTunnelRegs_size                  24
#define bdd_DebugRegs_size                       60
#define bdd_GpioDRegs_size                       66
#define bdd_I2cI2sRegs_size                      90
#define bdd_I2sCrossbarRegs_size                 244
#define bdd_IntRegs_size                         24
#define bdd_MailboxRegs_size                     12
#define bdd_MetaData_size                        211
#define bdd_NetworkPolicy_size                   32
#define bdd_Network_size                         28361
#define bdd_NodeDescriptor_size                  200
#define bdd_NodeSettings_size                    4
#define bdd_Node_size                            1650
#define bdd_PinIoRegs_size                       54
#define bdd_PwmRegs_size                         76
#define bdd_SpiRegs_size                         42
#define bdd_TuningRegs_size                      42
#define bdd_VmtrRegs_size                        111

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
