/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "bdd_pb2.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(bdd_MetaData, bdd_MetaData, AUTO)


PB_BIND(bdd_CustomNodeIdSettings, bdd_CustomNodeIdSettings, AUTO)


PB_BIND(bdd_NodeDescriptor, bdd_NodeDescriptor, AUTO)


PB_BIND(bdd_CtrlRegs, bdd_CtrlRegs, AUTO)


PB_BIND(bdd_VmtrRegs, bdd_VmtrRegs, AUTO)


PB_BIND(bdd_I2sCrossbarRegs, bdd_I2sCrossbarRegs, AUTO)


PB_BIND(bdd_PwmRegs, bdd_PwmRegs, AUTO)


PB_BIND(bdd_SpiRegs, bdd_SpiRegs, AUTO)


PB_BIND(bdd_DataTunnelRegs, bdd_DataTunnelRegs, AUTO)


PB_BIND(bdd_IntRegs, bdd_IntRegs, AUTO)


PB_BIND(bdd_TuningRegs, bdd_TuningRegs, AUTO)


PB_BIND(bdd_I2cI2sRegs, bdd_I2cI2sRegs, AUTO)


PB_BIND(bdd_PinIoRegs, bdd_PinIoRegs, AUTO)


PB_BIND(bdd_DataSlotEnhancementRegs, bdd_DataSlotEnhancementRegs, AUTO)


PB_BIND(bdd_GpioDRegs, bdd_GpioDRegs, AUTO)


PB_BIND(bdd_MailboxRegs, bdd_MailboxRegs, AUTO)


PB_BIND(bdd_DebugRegs, bdd_DebugRegs, AUTO)


PB_BIND(bdd_NodeSettings, bdd_NodeSettings, AUTO)


PB_BIND(bdd_Node, bdd_Node, 2)


PB_BIND(bdd_NetworkPolicy, bdd_NetworkPolicy, AUTO)


PB_BIND(bdd_Network, bdd_Network, 4)





















