//
//  phones.h
//  vsys
//
//  Created by 薯条 on 2018/1/19.
//  Copyright © 2018年 薯条. All rights reserved.
//

#ifndef PHONES_H
#define PHONES_H

const char phones[] =
"a1 a1_S\n"
"a2 a2_S\n"
"a3 a3_S\n"
"a4 a4_S\n"
"a5 a3_S\n"
"ai1 A1_B Y_E\n"
"ai2 A2_B Y_E\n"
"ai3 A3_B Y_E\n"
"ai4 A4_B Y_E\n"
"ai5 A3_B Y_E\n"
"an1 A1_B N_E\n"
"an2 A2_B N_E\n"
"an3 A3_B N_E\n"
"an4 A4_B N_E\n"
"an5 A3_B N_E\n"
"ang1 a1_B NG_E\n"
"ang2 a2_B NG_E\n"
"ang3 a3_B NG_E\n"
"ang4 a4_B NG_E\n"
"ang5 a3_B NG_E\n"
"ao1 a1_B W_E\n"
"ao2 a2_B W_E\n"
"ao3 a3_B W_E\n"
"ao4 a4_B W_E\n"
"ao5 a3_B W_E\n"
"ba1 b_B a1_E\n"
"ba2 b_B a2_E\n"
"ba3 b_B a3_E\n"
"ba4 b_B a4_E\n"
"ba5 b_B a3_E\n"
"bai1 b_B A1 Y_E\n"
"bai2 b_B A2 Y_E\n"
"bai3 b_B A3 Y_E\n"
"bai4 b_B A4 Y_E\n"
"bai5 b_B A3 Y_E\n"
"ban1 b_B A1 N_E\n"
"ban2 b_B A2 N_E\n"
"ban3 b_B A3 N_E\n"
"ban4 b_B A4 N_E\n"
"ban5 b_B A3 N_E\n"
"bang1 b_B a1 NG_E\n"
"bang2 b_B a2 NG_E\n"
"bang3 b_B a3 NG_E\n"
"bang4 b_B a4 NG_E\n"
"bang5 b_B a3 NG_E\n"
"bao1 b_B a1 W_E\n"
"bao2 b_B a2 W_E\n"
"bao3 b_B a3 W_E\n"
"bao4 b_B a4 W_E\n"
"bao5 b_B a3 W_E\n"
"bei1 b_B E1 Y_E\n"
"bei2 b_B E2 Y_E\n"
"bei3 b_B E3 Y_E\n"
"bei4 b_B E4 Y_E\n"
"bei5 b_B E3 Y_E\n"
"ben1 b_B e1 N_E\n"
"ben2 b_B e2 N_E\n"
"ben3 b_B e3 N_E\n"
"ben4 b_B e4 N_E\n"
"ben5 b_B e3 N_E\n"
"beng1 b_B e1 NG_E\n"
"beng2 b_B e2 NG_E\n"
"beng3 b_B e3 NG_E\n"
"beng4 b_B e4 NG_E\n"
"beng5 b_B e3 NG_E\n"
"bi1 b_B i1_E\n"
"bi2 b_B i2_E\n"
"bi3 b_B i3_E\n"
"bi4 b_B i4_E\n"
"bi5 b_B i3_E\n"
"bian1 b_B y A1 N_E\n"
"bian2 b_B y A2 N_E\n"
"bian3 b_B y A3 N_E\n"
"bian4 b_B y A4 N_E\n"
"bian5 b_B y A3 N_E\n"
"biao1 b_B y a1 W_E\n"
"biao2 b_B y a2 W_E\n"
"biao3 b_B y a3 W_E\n"
"biao4 b_B y a4 W_E\n"
"biao5 b_B y a3 W_E\n"
"bie1 b_B y E1_E\n"
"bie2 b_B y E2_E\n"
"bie3 b_B y E3_E\n"
"bie4 b_B y E4_E\n"
"bie5 b_B y E3_E\n"
"bin1 b_B i1 N_E\n"
"bin2 b_B i2 N_E\n"
"bin3 b_B i3 N_E\n"
"bin4 b_B i4 N_E\n"
"bin5 b_B i3 N_E\n"
"bing1 b_B i1 NG_E\n"
"bing2 b_B i2 NG_E\n"
"bing3 b_B i3 NG_E\n"
"bing4 b_B i4 NG_E\n"
"bing5 b_B i3 NG_E\n"
"bo1 b_B o1_E\n"
"bo2 b_B o2_E\n"
"bo3 b_B o3_E\n"
"bo4 b_B o4_E\n"
"bo5 b_B o3_E\n"
"bu1 b_B u1_E\n"
"bu2 b_B u2_E\n"
"bu3 b_B u3_E\n"
"bu4 b_B u4_E\n"
"bu5 b_B u3_E\n"
"ca1 c_B a1_E\n"
"ca2 c_B a2_E\n"
"ca3 c_B a3_E\n"
"ca4 c_B a4_E\n"
"ca5 c_B a3_E\n"
"cai1 c_B A1 Y_E\n"
"cai2 c_B A2 Y_E\n"
"cai3 c_B A3 Y_E\n"
"cai4 c_B A4 Y_E\n"
"cai5 c_B A3 Y_E\n"
"can1 c_B A1 N_E\n"
"can2 c_B A2 N_E\n"
"can3 c_B A3 N_E\n"
"can4 c_B A4 N_E\n"
"can5 c_B A3 N_E\n"
"cang1 c_B a1 NG_E\n"
"cang2 c_B a2 NG_E\n"
"cang3 c_B a3 NG_E\n"
"cang4 c_B a4 NG_E\n"
"cang5 c_B a3 NG_E\n"
"cao1 c_B a1 W_E\n"
"cao2 c_B a2 W_E\n"
"cao3 c_B a3 W_E\n"
"cao4 c_B a4 W_E\n"
"cao5 c_B a3 W_E\n"
"ce1 c_B e1_E\n"
"ce2 c_B e2_E\n"
"ce3 c_B e3_E\n"
"ce4 c_B e4_E\n"
"ce5 c_B e3_E\n"
"cen1 c_B e1 N_E\n"
"cen2 c_B e2 N_E\n"
"cen3 c_B e3 N_E\n"
"cen4 c_B e4 N_E\n"
"cen5 c_B e3 N_E\n"
"ceng1 c_B e1 NG_E\n"
"ceng2 c_B e2 NG_E\n"
"ceng3 c_B e3 NG_E\n"
"ceng4 c_B e4 NG_E\n"
"ceng5 c_B e3 NG_E\n"
"cha1 ch_B a1_E\n"
"cha2 ch_B a2_E\n"
"cha3 ch_B a3_E\n"
"cha4 ch_B a4_E\n"
"cha5 ch_B a3_E\n"
"chai1 ch_B A1 Y_E\n"
"chai2 ch_B A2 Y_E\n"
"chai3 ch_B A3 Y_E\n"
"chai4 ch_B A4 Y_E\n"
"chai5 ch_B A3 Y_E\n"
"chan1 ch_B A1 N_E\n"
"chan2 ch_B A2 N_E\n"
"chan3 ch_B A3 N_E\n"
"chan4 ch_B A4 N_E\n"
"chan5 ch_B A3 N_E\n"
"chang1 ch_B a1 NG_E\n"
"chang2 ch_B a2 NG_E\n"
"chang3 ch_B a3 NG_E\n"
"chang4 ch_B a4 NG_E\n"
"chang5 ch_B a3 NG_E\n"
"chao1 ch_B a1 W_E\n"
"chao2 ch_B a2 W_E\n"
"chao3 ch_B a3 W_E\n"
"chao4 ch_B a4 W_E\n"
"chao5 ch_B a3 W_E\n"
"che1 ch_B e1_E\n"
"che2 ch_B e2_E\n"
"che3 ch_B e3_E\n"
"che4 ch_B e4_E\n"
"che5 ch_B e3_E\n"
"chen1 ch_B e1 N_E\n"
"chen2 ch_B e2 N_E\n"
"chen3 ch_B e3 N_E\n"
"chen4 ch_B e4 N_E\n"
"chen5 ch_B e3 N_E\n"
"cheng1 ch_B e1 NG_E\n"
"cheng2 ch_B e2 NG_E\n"
"cheng3 ch_B e3 NG_E\n"
"cheng4 ch_B e4 NG_E\n"
"cheng5 ch_B e3 NG_E\n"
"chi1 ch_B IH1_E\n"
"chi2 ch_B IH2_E\n"
"chi3 ch_B IH3_E\n"
"chi4 ch_B IH4_E\n"
"chi5 ch_B IH3_E\n"
"chong1 ch_B o1 NG_E\n"
"chong2 ch_B o2 NG_E\n"
"chong3 ch_B o3 NG_E\n"
"chong4 ch_B o4 NG_E\n"
"chong5 ch_B o3 NG_E\n"
"chou1 ch_B o1 W_E\n"
"chou2 ch_B o2 W_E\n"
"chou3 ch_B o3 W_E\n"
"chou4 ch_B o4 W_E\n"
"chou5 ch_B o3 W_E\n"
"chu1 ch_B u1_E\n"
"chu2 ch_B u2_E\n"
"chu3 ch_B u3_E\n"
"chu4 ch_B u4_E\n"
"chu5 ch_B u3_E\n"
"chuai1 ch_B w A1 Y_E\n"
"chuai2 ch_B w A2 Y_E\n"
"chuai3 ch_B w A3 Y_E\n"
"chuai4 ch_B w A4 Y_E\n"
"chuai5 ch_B w A3 Y_E\n"
"chuan1 ch_B w A1 N_E\n"
"chuan2 ch_B w A2 N_E\n"
"chuan3 ch_B w A3 N_E\n"
"chuan4 ch_B w A4 N_E\n"
"chuan5 ch_B w A3 N_E\n"
"chuang1 ch_B w a1 NG_E\n"
"chuang2 ch_B w a2 NG_E\n"
"chuang3 ch_B w a3 NG_E\n"
"chuang4 ch_B w a4 NG_E\n"
"chuang5 ch_B w a3 NG_E\n"
"chui1 ch_B w E1 Y_E\n"
"chui2 ch_B w E2 Y_E\n"
"chui3 ch_B w E3 Y_E\n"
"chui4 ch_B w E4 Y_E\n"
"chui5 ch_B w E3 Y_E\n"
"chun1 ch_B w e1 N_E\n"
"chun2 ch_B w e2 N_E\n"
"chun3 ch_B w e3 N_E\n"
"chun4 ch_B w e4 N_E\n"
"chun5 ch_B w e3 N_E\n"
"chuo1 ch_B w o1_E\n"
"chuo2 ch_B w o2_E\n"
"chuo3 ch_B w o3_E\n"
"chuo4 ch_B w o4_E\n"
"chuo5 ch_B w o3_E\n"
"ci1 c_B I1_E\n"
"ci2 c_B I2_E\n"
"ci3 c_B I3_E\n"
"ci4 c_B I4_E\n"
"ci5 c_B I3_E\n"
"cong1 c_B o1 NG_E\n"
"cong2 c_B o2 NG_E\n"
"cong3 c_B o3 NG_E\n"
"cong4 c_B o4 NG_E\n"
"cong5 c_B o3 NG_E\n"
"cou1 c_B o1 W_E\n"
"cou2 c_B o2 W_E\n"
"cou3 c_B o3 W_E\n"
"cou4 c_B o4 W_E\n"
"cou5 c_B o3 W_E\n"
"cu1 c_B u1_E\n"
"cu2 c_B u2_E\n"
"cu3 c_B u3_E\n"
"cu4 c_B u4_E\n"
"cu5 c_B u3_E\n"
"cuan1 c_B w A1 N_E\n"
"cuan2 c_B w A2 N_E\n"
"cuan3 c_B w A3 N_E\n"
"cuan4 c_B w A4 N_E\n"
"cuan5 c_B w A3 N_E\n"
"cui1 c_B w E1 Y_E\n"
"cui2 c_B w E2 Y_E\n"
"cui3 c_B w E3 Y_E\n"
"cui4 c_B w E4 Y_E\n"
"cui5 c_B w E3 Y_E\n"
"cun1 c_B w e1 N_E\n"
"cun2 c_B w e2 N_E\n"
"cun3 c_B w e3 N_E\n"
"cun4 c_B w e4 N_E\n"
"cun5 c_B w e3 N_E\n"
"cuo1 c_B w o1_E\n"
"cuo2 c_B w o2_E\n"
"cuo3 c_B w o3_E\n"
"cuo4 c_B w o4_E\n"
"cuo5 c_B w o3_E\n"
"da1 d_B a1_E\n"
"da2 d_B a2_E\n"
"da3 d_B a3_E\n"
"da4 d_B a4_E\n"
"da5 d_B a3_E\n"
"dai1 d_B A1 Y_E\n"
"dai2 d_B A2 Y_E\n"
"dai3 d_B A3 Y_E\n"
"dai4 d_B A4 Y_E\n"
"dai5 d_B A3 Y_E\n"
"dan1 d_B A1 N_E\n"
"dan2 d_B A2 N_E\n"
"dan3 d_B A3 N_E\n"
"dan4 d_B A4 N_E\n"
"dan5 d_B A3 N_E\n"
"dang1 d_B a1 NG_E\n"
"dang2 d_B a2 NG_E\n"
"dang3 d_B a3 NG_E\n"
"dang4 d_B a4 NG_E\n"
"dang5 d_B a3 NG_E\n"
"dao1 d_B a1 W_E\n"
"dao2 d_B a2 W_E\n"
"dao3 d_B a3 W_E\n"
"dao4 d_B a4 W_E\n"
"dao5 d_B a3 W_E\n"
"de1 d_B e1_E\n"
"de2 d_B e2_E\n"
"de3 d_B e3_E\n"
"de4 d_B e4_E\n"
"de5 d_B e3_E\n"
"dei1 d_B E1 Y_E\n"
"dei2 d_B E2 Y_E\n"
"dei3 d_B E3 Y_E\n"
"dei4 d_B E4 Y_E\n"
"dei5 d_B E3 Y_E\n"
"deng1 d_B e1 NG_E\n"
"deng2 d_B e2 NG_E\n"
"deng3 d_B e3 NG_E\n"
"deng4 d_B e4 NG_E\n"
"deng5 d_B e3 NG_E\n"
"di1 d_B i1_E\n"
"di2 d_B i2_E\n"
"di3 d_B i3_E\n"
"di4 d_B i4_E\n"
"di5 d_B i3_E\n"
"dia1 d_B y A1_E\n"
"dia2 d_B y A2_E\n"
"dia3 d_B y A3_E\n"
"dia4 d_B y A4_E\n"
"dia5 d_B y A3_E\n"
"dian1 d_B y A1 N_E\n"
"dian2 d_B y A2 N_E\n"
"dian3 d_B y A3 N_E\n"
"dian4 d_B y A4 N_E\n"
"dian5 d_B y A3 N_E\n"
"diao1 d_B y a1 W_E\n"
"diao2 d_B y a2 W_E\n"
"diao3 d_B y a3 W_E\n"
"diao4 d_B y a4 W_E\n"
"diao5 d_B y a3 W_E\n"
"die1 d_B y E1_E\n"
"die2 d_B y E2_E\n"
"die3 d_B y E3_E\n"
"die4 d_B y E4_E\n"
"die5 d_B y E3_E\n"
"ding1 d_B i1 NG_E\n"
"ding2 d_B i2 NG_E\n"
"ding3 d_B i3 NG_E\n"
"ding4 d_B i4 NG_E\n"
"ding5 d_B i3 NG_E\n"
"diu1 d_B y o1 W_E\n"
"diu2 d_B y o2 W_E\n"
"diu3 d_B y o3 W_E\n"
"diu4 d_B y o4 W_E\n"
"diu5 d_B y o3 W_E\n"
"dong1 d_B o1 NG_E\n"
"dong2 d_B o2 NG_E\n"
"dong3 d_B o3 NG_E\n"
"dong4 d_B o4 NG_E\n"
"dong5 d_B o3 NG_E\n"
"dou1 d_B o1 W_E\n"
"dou2 d_B o2 W_E\n"
"dou3 d_B o3 W_E\n"
"dou4 d_B o4 W_E\n"
"dou5 d_B o3 W_E\n"
"du1 d_B u1_E\n"
"du2 d_B u2_E\n"
"du3 d_B u3_E\n"
"du4 d_B u4_E\n"
"du5 d_B u3_E\n"
"duan1 d_B w A1 N_E\n"
"duan2 d_B w A2 N_E\n"
"duan3 d_B w A3 N_E\n"
"duan4 d_B w A4 N_E\n"
"duan5 d_B w A3 N_E\n"
"dui1 d_B w E1 Y_E\n"
"dui2 d_B w E2 Y_E\n"
"dui3 d_B w E3 Y_E\n"
"dui4 d_B w E4 Y_E\n"
"dui5 d_B w E3 Y_E\n"
"dun1 d_B w e1 N_E\n"
"dun2 d_B w e2 N_E\n"
"dun3 d_B w e3 N_E\n"
"dun4 d_B w e4 N_E\n"
"dun5 d_B w e3 N_E\n"
"duo1 d_B w o1_E\n"
"duo2 d_B w o2_E\n"
"duo3 d_B w o3_E\n"
"duo4 d_B w o4_E\n"
"duo5 d_B w o3_E\n"
"e1 e1_S\n"
"e2 e2_S\n"
"e3 e3_S\n"
"e4 e4_S\n"
"e5 e3_S\n"
"ei1 E1_B Y_E\n"
"ei2 E2_B Y_E\n"
"ei3 E3_B Y_E\n"
"ei4 E4_B Y_E\n"
"ei5 E3_B Y_E\n"
"en1 e1_B N_E\n"
"en2 e2_B N_E\n"
"en3 e3_B N_E\n"
"en4 e4_B N_E\n"
"en5 e3_B N_E\n"
"eng1 e1_B NG_E\n"
"eng2 e2_B NG_E\n"
"eng3 e3_B NG_E\n"
"eng4 e4_B NG_E\n"
"eng5 e3_B NG_E\n"
"er1 er1_S\n"
"er2 er2_S\n"
"er3 er3_S\n"
"er4 er4_S\n"
"er5 er3_S\n"
"fa1 f_B a1_E\n"
"fa2 f_B a2_E\n"
"fa3 f_B a3_E\n"
"fa4 f_B a4_E\n"
"fa5 f_B a3_E\n"
"fan1 f_B A1 N_E\n"
"fan2 f_B A2 N_E\n"
"fan3 f_B A3 N_E\n"
"fan4 f_B A4 N_E\n"
"fan5 f_B A3 N_E\n"
"fang1 f_B a1 NG_E\n"
"fang2 f_B a2 NG_E\n"
"fang3 f_B a3 NG_E\n"
"fang4 f_B a4 NG_E\n"
"fang5 f_B a3 NG_E\n"
"fei1 f_B E1 Y_E\n"
"fei2 f_B E2 Y_E\n"
"fei3 f_B E3 Y_E\n"
"fei4 f_B E4 Y_E\n"
"fei5 f_B E3 Y_E\n"
"fen1 f_B e1 N_E\n"
"fen2 f_B e2 N_E\n"
"fen3 f_B e3 N_E\n"
"fen4 f_B e4 N_E\n"
"fen5 f_B e3 N_E\n"
"feng1 f_B e1 NG_E\n"
"feng2 f_B e2 NG_E\n"
"feng3 f_B e3 NG_E\n"
"feng4 f_B e4 NG_E\n"
"feng5 f_B e3 NG_E\n"
"fo1 f_B o1_E\n"
"fo2 f_B o2_E\n"
"fo3 f_B o3_E\n"
"fo4 f_B o4_E\n"
"fo5 f_B o3_E\n"
"fou1 f_B o1 W_E\n"
"fou2 f_B o2 W_E\n"
"fou3 f_B o3 W_E\n"
"fou4 f_B o4 W_E\n"
"fou5 f_B o3 W_E\n"
"fu1 f_B u1_E\n"
"fu2 f_B u2_E\n"
"fu3 f_B u3_E\n"
"fu4 f_B u4_E\n"
"fu5 f_B u3_E\n"
"ga1 g_B a1_E\n"
"ga2 g_B a2_E\n"
"ga3 g_B a3_E\n"
"ga4 g_B a4_E\n"
"ga5 g_B a3_E\n"
"gai1 g_B A1 Y_E\n"
"gai2 g_B A2 Y_E\n"
"gai3 g_B A3 Y_E\n"
"gai4 g_B A4 Y_E\n"
"gai5 g_B A3 Y_E\n"
"gan1 g_B A1 N_E\n"
"gan2 g_B A2 N_E\n"
"gan3 g_B A3 N_E\n"
"gan4 g_B A4 N_E\n"
"gan5 g_B A3 N_E\n"
"gang1 g_B a1 NG_E\n"
"gang2 g_B a2 NG_E\n"
"gang3 g_B a3 NG_E\n"
"gang4 g_B a4 NG_E\n"
"gang5 g_B a3 NG_E\n"
"gao1 g_B a1 W_E\n"
"gao2 g_B a2 W_E\n"
"gao3 g_B a3 W_E\n"
"gao4 g_B a4 W_E\n"
"gao5 g_B a3 W_E\n"
"ge1 g_B e1_E\n"
"ge2 g_B e2_E\n"
"ge3 g_B e3_E\n"
"ge4 g_B e4_E\n"
"ge5 g_B e3_E\n"
"gei1 g_B E1 Y_E\n"
"gei2 g_B E2 Y_E\n"
"gei3 g_B E3 Y_E\n"
"gei4 g_B E4 Y_E\n"
"gei5 g_B E3 Y_E\n"
"gen1 g_B e1 N_E\n"
"gen2 g_B e2 N_E\n"
"gen3 g_B e3 N_E\n"
"gen4 g_B e4 N_E\n"
"gen5 g_B e3 N_E\n"
"geng1 g_B e1 NG_E\n"
"geng2 g_B e2 NG_E\n"
"geng3 g_B e3 NG_E\n"
"geng4 g_B e4 NG_E\n"
"geng5 g_B e3 NG_E\n"
"gong1 g_B o1 NG_E\n"
"gong2 g_B o2 NG_E\n"
"gong3 g_B o3 NG_E\n"
"gong4 g_B o4 NG_E\n"
"gong5 g_B o3 NG_E\n"
"gou1 g_B o1 W_E\n"
"gou2 g_B o2 W_E\n"
"gou3 g_B o3 W_E\n"
"gou4 g_B o4 W_E\n"
"gou5 g_B o3 W_E\n"
"gu1 g_B u1_E\n"
"gu2 g_B u2_E\n"
"gu3 g_B u3_E\n"
"gu4 g_B u4_E\n"
"gu5 g_B u3_E\n"
"gua1 g_B w a1_E\n"
"gua2 g_B w a2_E\n"
"gua3 g_B w a3_E\n"
"gua4 g_B w a4_E\n"
"gua5 g_B w a3_E\n"
"guai1 g_B w A1 Y_E\n"
"guai2 g_B w A2 Y_E\n"
"guai3 g_B w A3 Y_E\n"
"guai4 g_B w A4 Y_E\n"
"guai5 g_B w A3 Y_E\n"
"guan1 g_B w A1 N_E\n"
"guan2 g_B w A2 N_E\n"
"guan3 g_B w A3 N_E\n"
"guan4 g_B w A4 N_E\n"
"guan5 g_B w A3 N_E\n"
"guang1 g_B w a1 NG_E\n"
"guang2 g_B w a2 NG_E\n"
"guang3 g_B w a3 NG_E\n"
"guang4 g_B w a4 NG_E\n"
"guang5 g_B w a3 NG_E\n"
"gui1 g_B w E1 Y_E\n"
"gui2 g_B w E2 Y_E\n"
"gui3 g_B w E3 Y_E\n"
"gui4 g_B w E4 Y_E\n"
"gui5 g_B w E3 Y_E\n"
"gun1 g_B w e1 N_E\n"
"gun2 g_B w e2 N_E\n"
"gun3 g_B w e3 N_E\n"
"gun4 g_B w e4 N_E\n"
"gun5 g_B w e3 N_E\n"
"guo1 g_B w o1_E\n"
"guo2 g_B w o2_E\n"
"guo3 g_B w o3_E\n"
"guo4 g_B w o4_E\n"
"guo5 g_B w o3_E\n"
"ha1 h_B a1_E\n"
"ha2 h_B a2_E\n"
"ha3 h_B a3_E\n"
"ha4 h_B a4_E\n"
"ha5 h_B a3_E\n"
"hai1 h_B A1 Y_E\n"
"hai2 h_B A2 Y_E\n"
"hai3 h_B A3 Y_E\n"
"hai4 h_B A4 Y_E\n"
"hai5 h_B A3 Y_E\n"
"han1 h_B A1 N_E\n"
"han2 h_B A2 N_E\n"
"han3 h_B A3 N_E\n"
"han4 h_B A4 N_E\n"
"han5 h_B A3 N_E\n"
"hang1 h_B a1 NG_E\n"
"hang2 h_B a2 NG_E\n"
"hang3 h_B a3 NG_E\n"
"hang4 h_B a4 NG_E\n"
"hang5 h_B a3 NG_E\n"
"hao1 h_B a1 W_E\n"
"hao2 h_B a2 W_E\n"
"hao3 h_B a3 W_E\n"
"hao4 h_B a4 W_E\n"
"hao5 h_B a3 W_E\n"
"he1 h_B e1_E\n"
"he2 h_B e2_E\n"
"he3 h_B e3_E\n"
"he4 h_B e4_E\n"
"he5 h_B e3_E\n"
"hei1 h_B E1 Y_E\n"
"hei2 h_B E2 Y_E\n"
"hei3 h_B E3 Y_E\n"
"hei4 h_B E4 Y_E\n"
"hei5 h_B E3 Y_E\n"
"hen1 h_B e1 N_E\n"
"hen2 h_B e2 N_E\n"
"hen3 h_B e3 N_E\n"
"hen4 h_B e4 N_E\n"
"hen5 h_B e3 N_E\n"
"heng1 h_B e1 NG_E\n"
"heng2 h_B e2 NG_E\n"
"heng3 h_B e3 NG_E\n"
"heng4 h_B e4 NG_E\n"
"heng5 h_B e3 NG_E\n"
"hong1 h_B o1 NG_E\n"
"hong2 h_B o2 NG_E\n"
"hong3 h_B o3 NG_E\n"
"hong4 h_B o4 NG_E\n"
"hong5 h_B o3 NG_E\n"
"hou1 h_B o1 W_E\n"
"hou2 h_B o2 W_E\n"
"hou3 h_B o3 W_E\n"
"hou4 h_B o4 W_E\n"
"hou5 h_B o3 W_E\n"
"hu1 h_B u1_E\n"
"hu2 h_B u2_E\n"
"hu3 h_B u3_E\n"
"hu4 h_B u4_E\n"
"hu5 h_B u3_E\n"
"hua1 h_B w a1_E\n"
"hua2 h_B w a2_E\n"
"hua3 h_B w a3_E\n"
"hua4 h_B w a4_E\n"
"hua5 h_B w a3_E\n"
"huai1 h_B w A1 Y_E\n"
"huai2 h_B w A2 Y_E\n"
"huai3 h_B w A3 Y_E\n"
"huai4 h_B w A4 Y_E\n"
"huai5 h_B w A3 Y_E\n"
"huan1 h_B w A1 N_E\n"
"huan2 h_B w A2 N_E\n"
"huan3 h_B w A3 N_E\n"
"huan4 h_B w A4 N_E\n"
"huan5 h_B w A3 N_E\n"
"huang1 h_B w a1 NG_E\n"
"huang2 h_B w a2 NG_E\n"
"huang3 h_B w a3 NG_E\n"
"huang4 h_B w a4 NG_E\n"
"huang5 h_B w a3 NG_E\n"
"hui1 h_B w E1 Y_E\n"
"hui2 h_B w E2 Y_E\n"
"hui3 h_B w E3 Y_E\n"
"hui4 h_B w E4 Y_E\n"
"hui5 h_B w E3 Y_E\n"
"hun1 h_B w e1 N_E\n"
"hun2 h_B w e2 N_E\n"
"hun3 h_B w e3 N_E\n"
"hun4 h_B w e4 N_E\n"
"hun5 h_B w e3 N_E\n"
"huo1 h_B w o1_E\n"
"huo2 h_B w o2_E\n"
"huo3 h_B w o3_E\n"
"huo4 h_B w o4_E\n"
"huo5 h_B w o3_E\n"
"ji1 j_B i1_E\n"
"ji2 j_B i2_E\n"
"ji3 j_B i3_E\n"
"ji4 j_B i4_E\n"
"ji5 j_B i3_E\n"
"jia1 j_B y A1_E\n"
"jia2 j_B y A2_E\n"
"jia3 j_B y A3_E\n"
"jia4 j_B y A4_E\n"
"jia5 j_B y A3_E\n"
"jian1 j_B y A1 N_E\n"
"jian2 j_B y A2 N_E\n"
"jian3 j_B y A3 N_E\n"
"jian4 j_B y A4 N_E\n"
"jian5 j_B y A3 N_E\n"
"jiang1 j_B y a1 NG_E\n"
"jiang2 j_B y a2 NG_E\n"
"jiang3 j_B y a3 NG_E\n"
"jiang4 j_B y a4 NG_E\n"
"jiang5 j_B y a3 NG_E\n"
"jiao1 j_B y a1 W_E\n"
"jiao2 j_B y a2 W_E\n"
"jiao3 j_B y a3 W_E\n"
"jiao4 j_B y a4 W_E\n"
"jiao5 j_B y a3 W_E\n"
"jie1 j_B y E1_E\n"
"jie2 j_B y E2_E\n"
"jie3 j_B y E3_E\n"
"jie4 j_B y E4_E\n"
"jie5 j_B y E3_E\n"
"jin1 j_B i1 N_E\n"
"jin2 j_B i2 N_E\n"
"jin3 j_B i3 N_E\n"
"jin4 j_B i4 N_E\n"
"jin5 j_B i3 N_E\n"
"jing1 j_B i1 NG_E\n"
"jing2 j_B i2 NG_E\n"
"jing3 j_B i3 NG_E\n"
"jing4 j_B i4 NG_E\n"
"jing5 j_B i3 NG_E\n"
"jiong1 j_B y o1 NG_E\n"
"jiong2 j_B y o2 NG_E\n"
"jiong3 j_B y o3 NG_E\n"
"jiong4 j_B y o4 NG_E\n"
"jiong5 j_B y o3 NG_E\n"
"jiu1 j_B y o1 W_E\n"
"jiu2 j_B y o2 W_E\n"
"jiu3 j_B y o3 W_E\n"
"jiu4 j_B y o4 W_E\n"
"jiu5 j_B y o3 W_E\n"
"ju1 j_B yu1_E\n"
"ju2 j_B yu2_E\n"
"ju3 j_B yu3_E\n"
"ju4 j_B yu4_E\n"
"ju5 j_B yu3_E\n"
"juan1 j_B v A1 N_E\n"
"juan2 j_B v A2 N_E\n"
"juan3 j_B v A3 N_E\n"
"juan4 j_B v A4 N_E\n"
"juan5 j_B v A3 N_E\n"
"jue1 j_B v E1_E\n"
"jue2 j_B v E2_E\n"
"jue3 j_B v E3_E\n"
"jue4 j_B v E4_E\n"
"jue5 j_B v E3_E\n"
"jun1 j_B v e1 N_E\n"
"jun2 j_B v e2 N_E\n"
"jun3 j_B v e3 N_E\n"
"jun4 j_B v e4 N_E\n"
"jun5 j_B v e3 N_E\n"
"ka1 k_B a1_E\n"
"ka2 k_B a2_E\n"
"ka3 k_B a3_E\n"
"ka4 k_B a4_E\n"
"ka5 k_B a3_E\n"
"kai1 k_B A1 Y_E\n"
"kai2 k_B A2 Y_E\n"
"kai3 k_B A3 Y_E\n"
"kai4 k_B A4 Y_E\n"
"kai5 k_B A3 Y_E\n"
"kan1 k_B A1 N_E\n"
"kan2 k_B A2 N_E\n"
"kan3 k_B A3 N_E\n"
"kan4 k_B A4 N_E\n"
"kan5 k_B A3 N_E\n"
"kang1 k_B a1 NG_E\n"
"kang2 k_B a2 NG_E\n"
"kang3 k_B a3 NG_E\n"
"kang4 k_B a4 NG_E\n"
"kang5 k_B a3 NG_E\n"
"kao1 k_B a1 W_E\n"
"kao2 k_B a2 W_E\n"
"kao3 k_B a3 W_E\n"
"kao4 k_B a4 W_E\n"
"kao5 k_B a3 W_E\n"
"ke1 k_B e1_E\n"
"ke2 k_B e2_E\n"
"ke3 k_B e3_E\n"
"ke4 k_B e4_E\n"
"ke5 k_B e3_E\n"
"ken1 k_B e1 N_E\n"
"ken2 k_B e2 N_E\n"
"ken3 k_B e3 N_E\n"
"ken4 k_B e4 N_E\n"
"ken5 k_B e3 N_E\n"
"keng1 k_B e1 NG_E\n"
"keng2 k_B e2 NG_E\n"
"keng3 k_B e3 NG_E\n"
"keng4 k_B e4 NG_E\n"
"keng5 k_B e3 NG_E\n"
"kong1 k_B o1 NG_E\n"
"kong2 k_B o2 NG_E\n"
"kong3 k_B o3 NG_E\n"
"kong4 k_B o4 NG_E\n"
"kong5 k_B o3 NG_E\n"
"kou1 k_B o1 W_E\n"
"kou2 k_B o2 W_E\n"
"kou3 k_B o3 W_E\n"
"kou4 k_B o4 W_E\n"
"kou5 k_B o3 W_E\n"
"ku1 k_B u1_E\n"
"ku2 k_B u2_E\n"
"ku3 k_B u3_E\n"
"ku4 k_B u4_E\n"
"ku5 k_B u3_E\n"
"kua1 k_B w a1_E\n"
"kua2 k_B w a2_E\n"
"kua3 k_B w a3_E\n"
"kua4 k_B w a4_E\n"
"kua5 k_B w a3_E\n"
"kuai1 k_B w A1 Y_E\n"
"kuai2 k_B w A2 Y_E\n"
"kuai3 k_B w A3 Y_E\n"
"kuai4 k_B w A4 Y_E\n"
"kuai5 k_B w A3 Y_E\n"
"kuan1 k_B w A1 N_E\n"
"kuan2 k_B w A2 N_E\n"
"kuan3 k_B w A3 N_E\n"
"kuan4 k_B w A4 N_E\n"
"kuan5 k_B w A3 N_E\n"
"kuang1 k_B w a1 NG_E\n"
"kuang2 k_B w a2 NG_E\n"
"kuang3 k_B w a3 NG_E\n"
"kuang4 k_B w a4 NG_E\n"
"kuang5 k_B w a3 NG_E\n"
"kui1 k_B w E1 Y_E\n"
"kui2 k_B w E2 Y_E\n"
"kui3 k_B w E3 Y_E\n"
"kui4 k_B w E4 Y_E\n"
"kui5 k_B w E3 Y_E\n"
"kun1 k_B w e1 N_E\n"
"kun2 k_B w e2 N_E\n"
"kun3 k_B w e3 N_E\n"
"kun4 k_B w e4 N_E\n"
"kun5 k_B w e3 N_E\n"
"kuo1 k_B w o1_E\n"
"kuo2 k_B w o2_E\n"
"kuo3 k_B w o3_E\n"
"kuo4 k_B w o4_E\n"
"kuo5 k_B w o3_E\n"
"la1 l_B a1_E\n"
"la2 l_B a2_E\n"
"la3 l_B a3_E\n"
"la4 l_B a4_E\n"
"la5 l_B a3_E\n"
"lai1 l_B A1 Y_E\n"
"lai2 l_B A2 Y_E\n"
"lai3 l_B A3 Y_E\n"
"lai4 l_B A4 Y_E\n"
"lai5 l_B A3 Y_E\n"
"lan1 l_B A1 N_E\n"
"lan2 l_B A2 N_E\n"
"lan3 l_B A3 N_E\n"
"lan4 l_B A4 N_E\n"
"lan5 l_B A3 N_E\n"
"lang1 l_B a1 NG_E\n"
"lang2 l_B a2 NG_E\n"
"lang3 l_B a3 NG_E\n"
"lang4 l_B a4 NG_E\n"
"lang5 l_B a3 NG_E\n"
"lao1 l_B a1 W_E\n"
"lao2 l_B a2 W_E\n"
"lao3 l_B a3 W_E\n"
"lao4 l_B a4 W_E\n"
"lao5 l_B a3 W_E\n"
"le1 l_B e1_E\n"
"le2 l_B e2_E\n"
"le3 l_B e3_E\n"
"le4 l_B e4_E\n"
"le5 l_B e3_E\n"
"lei1 l_B E1 Y_E\n"
"lei2 l_B E2 Y_E\n"
"lei3 l_B E3 Y_E\n"
"lei4 l_B E4 Y_E\n"
"lei5 l_B E3 Y_E\n"
"leng1 l_B e1 NG_E\n"
"leng2 l_B e2 NG_E\n"
"leng3 l_B e3 NG_E\n"
"leng4 l_B e4 NG_E\n"
"leng5 l_B e3 NG_E\n"
"li1 l_B i1_E\n"
"li2 l_B i2_E\n"
"li3 l_B i3_E\n"
"li4 l_B i4_E\n"
"li5 l_B i3_E\n"
"lia1 l_B y A1_E\n"
"lia2 l_B y A2_E\n"
"lia3 l_B y A3_E\n"
"lia4 l_B y A4_E\n"
"lia5 l_B y A3_E\n"
"lian1 l_B y A1 N_E\n"
"lian2 l_B y A2 N_E\n"
"lian3 l_B y A3 N_E\n"
"lian4 l_B y A4 N_E\n"
"lian5 l_B y A3 N_E\n"
"liang1 l_B y a1 NG_E\n"
"liang2 l_B y a2 NG_E\n"
"liang3 l_B y a3 NG_E\n"
"liang4 l_B y a4 NG_E\n"
"liang5 l_B y a3 NG_E\n"
"liao1 l_B y a1 W_E\n"
"liao2 l_B y a2 W_E\n"
"liao3 l_B y a3 W_E\n"
"liao4 l_B y a4 W_E\n"
"liao5 l_B y a3 W_E\n"
"lie1 l_B y E1_E\n"
"lie2 l_B y E2_E\n"
"lie3 l_B y E3_E\n"
"lie4 l_B y E4_E\n"
"lie5 l_B y E3_E\n"
"lin1 l_B i1 N_E\n"
"lin2 l_B i2 N_E\n"
"lin3 l_B i3 N_E\n"
"lin4 l_B i4 N_E\n"
"lin5 l_B i3 N_E\n"
"ling1 l_B i1 NG_E\n"
"ling2 l_B i2 NG_E\n"
"ling3 l_B i3 NG_E\n"
"ling4 l_B i4 NG_E\n"
"ling5 l_B i3 NG_E\n"
"liu1 l_B y o1 W_E\n"
"liu2 l_B y o2 W_E\n"
"liu3 l_B y o3 W_E\n"
"liu4 l_B y o4 W_E\n"
"liu5 l_B y o3 W_E\n"
"lo1 l_B o1_E\n"
"lo2 l_B o2_E\n"
"lo3 l_B o3_E\n"
"lo4 l_B o4_E\n"
"lo5 l_B o3_E\n"
"long1 l_B o1 NG_E\n"
"long2 l_B o2 NG_E\n"
"long3 l_B o3 NG_E\n"
"long4 l_B o4 NG_E\n"
"long5 l_B o3 NG_E\n"
"lou1 l_B o1 W_E\n"
"lou2 l_B o2 W_E\n"
"lou3 l_B o3 W_E\n"
"lou4 l_B o4 W_E\n"
"lou5 l_B o3 W_E\n"
"lu1 l_B u1_E\n"
"lu2 l_B u2_E\n"
"lu3 l_B u3_E\n"
"lu4 l_B u4_E\n"
"lu5 l_B u3_E\n"
"luan1 l_B w A1 N_E\n"
"luan2 l_B w A2 N_E\n"
"luan3 l_B w A3 N_E\n"
"luan4 l_B w A4 N_E\n"
"luan5 l_B w A3 N_E\n"
"lun1 l_B w e1 N_E\n"
"lun2 l_B w e2 N_E\n"
"lun3 l_B w e3 N_E\n"
"lun4 l_B w e4 N_E\n"
"lun5 l_B w e3 N_E\n"
"luo1 l_B w o1_E\n"
"luo2 l_B w o2_E\n"
"luo3 l_B w o3_E\n"
"luo4 l_B w o4_E\n"
"luo5 l_B w o3_E\n"
"lv1 l_B yu1_E\n"
"lv2 l_B yu2_E\n"
"lv3 l_B yu3_E\n"
"lv4 l_B yu4_E\n"
"lv5 l_B yu3_E\n"
"lve1 l_B v E1_E\n"
"lve2 l_B v E2_E\n"
"lve3 l_B v E3_E\n"
"lve4 l_B v E4_E\n"
"lve5 l_B v E3_E\n"
"ma1 m_B a1_E\n"
"ma2 m_B a2_E\n"
"ma3 m_B a3_E\n"
"ma4 m_B a4_E\n"
"ma5 m_B a3_E\n"
"mai1 m_B A1 Y_E\n"
"mai2 m_B A2 Y_E\n"
"mai3 m_B A3 Y_E\n"
"mai4 m_B A4 Y_E\n"
"mai5 m_B A3 Y_E\n"
"man1 m_B A1 N_E\n"
"man2 m_B A2 N_E\n"
"man3 m_B A3 N_E\n"
"man4 m_B A4 N_E\n"
"man5 m_B A3 N_E\n"
"mang1 m_B a1 NG_E\n"
"mang2 m_B a2 NG_E\n"
"mang3 m_B a3 NG_E\n"
"mang4 m_B a4 NG_E\n"
"mang5 m_B a3 NG_E\n"
"mao1 m_B a1 W_E\n"
"mao2 m_B a2 W_E\n"
"mao3 m_B a3 W_E\n"
"mao4 m_B a4 W_E\n"
"mao5 m_B a3 W_E\n"
"me1 m_B e1_E\n"
"me2 m_B e2_E\n"
"me3 m_B e3_E\n"
"me4 m_B e4_E\n"
"me5 m_B e3_E\n"
"mei1 m_B E1 Y_E\n"
"mei2 m_B E2 Y_E\n"
"mei3 m_B E3 Y_E\n"
"mei4 m_B E4 Y_E\n"
"mei5 m_B E3 Y_E\n"
"men1 m_B e1 N_E\n"
"men2 m_B e2 N_E\n"
"men3 m_B e3 N_E\n"
"men4 m_B e4 N_E\n"
"men5 m_B e3 N_E\n"
"meng1 m_B e1 NG_E\n"
"meng2 m_B e2 NG_E\n"
"meng3 m_B e3 NG_E\n"
"meng4 m_B e4 NG_E\n"
"meng5 m_B e3 NG_E\n"
"mi1 m_B i1_E\n"
"mi2 m_B i2_E\n"
"mi3 m_B i3_E\n"
"mi4 m_B i4_E\n"
"mi5 m_B i3_E\n"
"mian1 m_B y A1 N_E\n"
"mian2 m_B y A2 N_E\n"
"mian3 m_B y A3 N_E\n"
"mian4 m_B y A4 N_E\n"
"mian5 m_B y A3 N_E\n"
"miao1 m_B y a1 W_E\n"
"miao2 m_B y a2 W_E\n"
"miao3 m_B y a3 W_E\n"
"miao4 m_B y a4 W_E\n"
"miao5 m_B y a3 W_E\n"
"mie1 m_B y E1_E\n"
"mie2 m_B y E2_E\n"
"mie3 m_B y E3_E\n"
"mie4 m_B y E4_E\n"
"mie5 m_B y E3_E\n"
"min1 m_B i1 N_E\n"
"min2 m_B i2 N_E\n"
"min3 m_B i3 N_E\n"
"min4 m_B i4 N_E\n"
"min5 m_B i3 N_E\n"
"ming1 m_B i1 NG_E\n"
"ming2 m_B i2 NG_E\n"
"ming3 m_B i3 NG_E\n"
"ming4 m_B i4 NG_E\n"
"ming5 m_B i3 NG_E\n"
"miu1 m_B y o1 W_E\n"
"miu2 m_B y o2 W_E\n"
"miu3 m_B y o3 W_E\n"
"miu4 m_B y o4 W_E\n"
"miu5 m_B y o3 W_E\n"
"mo1 m_B o1_E\n"
"mo2 m_B o2_E\n"
"mo3 m_B o3_E\n"
"mo4 m_B o4_E\n"
"mo5 m_B o3_E\n"
"mou1 m_B o1 W_E\n"
"mou2 m_B o2 W_E\n"
"mou3 m_B o3 W_E\n"
"mou4 m_B o4 W_E\n"
"mou5 m_B o3 W_E\n"
"mu1 m_B u1_E\n"
"mu2 m_B u2_E\n"
"mu3 m_B u3_E\n"
"mu4 m_B u4_E\n"
"mu5 m_B u3_E\n"
"na1 n_B a1_E\n"
"na2 n_B a2_E\n"
"na3 n_B a3_E\n"
"na4 n_B a4_E\n"
"na5 n_B a3_E\n"
"nai1 n_B A1 Y_E\n"
"nai2 n_B A2 Y_E\n"
"nai3 n_B A3 Y_E\n"
"nai4 n_B A4 Y_E\n"
"nai5 n_B A3 Y_E\n"
"nan1 n_B A1 N_E\n"
"nan2 n_B A2 N_E\n"
"nan3 n_B A3 N_E\n"
"nan4 n_B A4 N_E\n"
"nan5 n_B A3 N_E\n"
"nang1 n_B a1 NG_E\n"
"nang2 n_B a2 NG_E\n"
"nang3 n_B a3 NG_E\n"
"nang4 n_B a4 NG_E\n"
"nang5 n_B a3 NG_E\n"
"nao1 n_B a1 W_E\n"
"nao2 n_B a2 W_E\n"
"nao3 n_B a3 W_E\n"
"nao4 n_B a4 W_E\n"
"nao5 n_B a3 W_E\n"
"ne1 n_B e1_E\n"
"ne2 n_B e2_E\n"
"ne3 n_B e3_E\n"
"ne4 n_B e4_E\n"
"ne5 n_B e3_E\n"
"nei1 n_B E1 Y_E\n"
"nei2 n_B E2 Y_E\n"
"nei3 n_B E3 Y_E\n"
"nei4 n_B E4 Y_E\n"
"nei5 n_B E3 Y_E\n"
"nen1 n_B e1 N_E\n"
"nen2 n_B e2 N_E\n"
"nen3 n_B e3 N_E\n"
"nen4 n_B e4 N_E\n"
"nen5 n_B e3 N_E\n"
"neng1 n_B e1 NG_E\n"
"neng2 n_B e2 NG_E\n"
"neng3 n_B e3 NG_E\n"
"neng4 n_B e4 NG_E\n"
"neng5 n_B e3 NG_E\n"
"ni1 n_B i1_E\n"
"ni2 n_B i2_E\n"
"ni3 n_B i3_E\n"
"ni4 n_B i4_E\n"
"ni5 n_B i3_E\n"
"nian1 n_B y A1 N_E\n"
"nian2 n_B y A2 N_E\n"
"nian3 n_B y A3 N_E\n"
"nian4 n_B y A4 N_E\n"
"nian5 n_B y A3 N_E\n"
"niang1 n_B y a1 NG_E\n"
"niang2 n_B y a2 NG_E\n"
"niang3 n_B y a3 NG_E\n"
"niang4 n_B y a4 NG_E\n"
"niang5 n_B y a3 NG_E\n"
"niao1 n_B y a1 W_E\n"
"niao2 n_B y a2 W_E\n"
"niao3 n_B y a3 W_E\n"
"niao4 n_B y a4 W_E\n"
"niao5 n_B y a3 W_E\n"
"nie1 n_B y E1_E\n"
"nie2 n_B y E2_E\n"
"nie3 n_B y E3_E\n"
"nie4 n_B y E4_E\n"
"nie5 n_B y E3_E\n"
"nin1 n_B i1 N_E\n"
"nin2 n_B i2 N_E\n"
"nin3 n_B i3 N_E\n"
"nin4 n_B i4 N_E\n"
"nin5 n_B i3 N_E\n"
"ning1 n_B i1 NG_E\n"
"ning2 n_B i2 NG_E\n"
"ning3 n_B i3 NG_E\n"
"ning4 n_B i4 NG_E\n"
"ning5 n_B i3 NG_E\n"
"niu1 n_B y o1 W_E\n"
"niu2 n_B y o2 W_E\n"
"niu3 n_B y o3 W_E\n"
"niu4 n_B y o4 W_E\n"
"niu5 n_B y o3 W_E\n"
"nong1 n_B o1 NG_E\n"
"nong2 n_B o2 NG_E\n"
"nong3 n_B o3 NG_E\n"
"nong4 n_B o4 NG_E\n"
"nong5 n_B o3 NG_E\n"
"nou1 n_B o1 W_E\n"
"nou2 n_B o2 W_E\n"
"nou3 n_B o3 W_E\n"
"nou4 n_B o4 W_E\n"
"nou5 n_B o3 W_E\n"
"nu1 n_B u1_E\n"
"nu2 n_B u2_E\n"
"nu3 n_B u3_E\n"
"nu4 n_B u4_E\n"
"nu5 n_B u3_E\n"
"nuan1 n_B w A1 N_E\n"
"nuan2 n_B w A2 N_E\n"
"nuan3 n_B w A3 N_E\n"
"nuan4 n_B w A4 N_E\n"
"nuan5 n_B w A3 N_E\n"
"nuo1 n_B w o1_E\n"
"nuo2 n_B w o2_E\n"
"nuo3 n_B w o3_E\n"
"nuo4 n_B w o4_E\n"
"nuo5 n_B w o3_E\n"
"nv1 n_B yu1_E\n"
"nv2 n_B yu2_E\n"
"nv3 n_B yu3_E\n"
"nv4 n_B yu4_E\n"
"nv5 n_B yu3_E\n"
"nve1 n_B v E1_E\n"
"nve2 n_B v E2_E\n"
"nve3 n_B v E3_E\n"
"nve4 n_B v E4_E\n"
"nve5 n_B v E3_E\n"
"o1 o1_S\n"
"o2 o2_S\n"
"o3 o3_S\n"
"o4 o4_S\n"
"o5 o3_S\n"
"ou1 o1_B W_E\n"
"ou2 o2_B W_E\n"
"ou3 o3_B W_E\n"
"ou4 o4_B W_E\n"
"ou5 o3_B W_E\n"
"pa1 p_B a1_E\n"
"pa2 p_B a2_E\n"
"pa3 p_B a3_E\n"
"pa4 p_B a4_E\n"
"pa5 p_B a3_E\n"
"pai1 p_B A1 Y_E\n"
"pai2 p_B A2 Y_E\n"
"pai3 p_B A3 Y_E\n"
"pai4 p_B A4 Y_E\n"
"pai5 p_B A3 Y_E\n"
"pan1 p_B A1 N_E\n"
"pan2 p_B A2 N_E\n"
"pan3 p_B A3 N_E\n"
"pan4 p_B A4 N_E\n"
"pan5 p_B A3 N_E\n"
"pang1 p_B a1 NG_E\n"
"pang2 p_B a2 NG_E\n"
"pang3 p_B a3 NG_E\n"
"pang4 p_B a4 NG_E\n"
"pang5 p_B a3 NG_E\n"
"pao1 p_B a1 W_E\n"
"pao2 p_B a2 W_E\n"
"pao3 p_B a3 W_E\n"
"pao4 p_B a4 W_E\n"
"pao5 p_B a3 W_E\n"
"pei1 p_B E1 Y_E\n"
"pei2 p_B E2 Y_E\n"
"pei3 p_B E3 Y_E\n"
"pei4 p_B E4 Y_E\n"
"pei5 p_B E3 Y_E\n"
"pen1 p_B e1 N_E\n"
"pen2 p_B e2 N_E\n"
"pen3 p_B e3 N_E\n"
"pen4 p_B e4 N_E\n"
"pen5 p_B e3 N_E\n"
"peng1 p_B e1 NG_E\n"
"peng2 p_B e2 NG_E\n"
"peng3 p_B e3 NG_E\n"
"peng4 p_B e4 NG_E\n"
"peng5 p_B e3 NG_E\n"
"pi1 p_B i1_E\n"
"pi2 p_B i2_E\n"
"pi3 p_B i3_E\n"
"pi4 p_B i4_E\n"
"pi5 p_B i3_E\n"
"pian1 p_B y A1 N_E\n"
"pian2 p_B y A2 N_E\n"
"pian3 p_B y A3 N_E\n"
"pian4 p_B y A4 N_E\n"
"pian5 p_B y A3 N_E\n"
"piao1 p_B y a1 W_E\n"
"piao2 p_B y a2 W_E\n"
"piao3 p_B y a3 W_E\n"
"piao4 p_B y a4 W_E\n"
"piao5 p_B y a3 W_E\n"
"pie1 p_B y E1_E\n"
"pie2 p_B y E2_E\n"
"pie3 p_B y E3_E\n"
"pie4 p_B y E4_E\n"
"pie5 p_B y E3_E\n"
"pin1 p_B i1 N_E\n"
"pin2 p_B i2 N_E\n"
"pin3 p_B i3 N_E\n"
"pin4 p_B i4 N_E\n"
"pin5 p_B i3 N_E\n"
"ping1 p_B i1 NG_E\n"
"ping2 p_B i2 NG_E\n"
"ping3 p_B i3 NG_E\n"
"ping4 p_B i4 NG_E\n"
"ping5 p_B i3 NG_E\n"
"po1 p_B o1_E\n"
"po2 p_B o2_E\n"
"po3 p_B o3_E\n"
"po4 p_B o4_E\n"
"po5 p_B o3_E\n"
"pou1 p_B o1 W_E\n"
"pou2 p_B o2 W_E\n"
"pou3 p_B o3 W_E\n"
"pou4 p_B o4 W_E\n"
"pou5 p_B o3 W_E\n"
"pu1 p_B u1_E\n"
"pu2 p_B u2_E\n"
"pu3 p_B u3_E\n"
"pu4 p_B u4_E\n"
"pu5 p_B u3_E\n"
"qi1 q_B i1_E\n"
"qi2 q_B i2_E\n"
"qi3 q_B i3_E\n"
"qi4 q_B i4_E\n"
"qi5 q_B i3_E\n"
"qia1 q_B y A1_E\n"
"qia2 q_B y A2_E\n"
"qia3 q_B y A3_E\n"
"qia4 q_B y A4_E\n"
"qia5 q_B y A3_E\n"
"qian1 q_B y A1 N_E\n"
"qian2 q_B y A2 N_E\n"
"qian3 q_B y A3 N_E\n"
"qian4 q_B y A4 N_E\n"
"qian5 q_B y A3 N_E\n"
"qiang1 q_B y a1 NG_E\n"
"qiang2 q_B y a2 NG_E\n"
"qiang3 q_B y a3 NG_E\n"
"qiang4 q_B y a4 NG_E\n"
"qiang5 q_B y a3 NG_E\n"
"qiao1 q_B y a1 W_E\n"
"qiao2 q_B y a2 W_E\n"
"qiao3 q_B y a3 W_E\n"
"qiao4 q_B y a4 W_E\n"
"qiao5 q_B y a3 W_E\n"
"qie1 q_B y E1_E\n"
"qie2 q_B y E2_E\n"
"qie3 q_B y E3_E\n"
"qie4 q_B y E4_E\n"
"qie5 q_B y E3_E\n"
"qin1 q_B i1 N_E\n"
"qin2 q_B i2 N_E\n"
"qin3 q_B i3 N_E\n"
"qin4 q_B i4 N_E\n"
"qin5 q_B i3 N_E\n"
"qing1 q_B i1 NG_E\n"
"qing2 q_B i2 NG_E\n"
"qing3 q_B i3 NG_E\n"
"qing4 q_B i4 NG_E\n"
"qing5 q_B i3 NG_E\n"
"qiong1 q_B y o1 NG_E\n"
"qiong2 q_B y o2 NG_E\n"
"qiong3 q_B y o3 NG_E\n"
"qiong4 q_B y o4 NG_E\n"
"qiong5 q_B y o3 NG_E\n"
"qiu1 q_B y o1 W_E\n"
"qiu2 q_B y o2 W_E\n"
"qiu3 q_B y o3 W_E\n"
"qiu4 q_B y o4 W_E\n"
"qiu5 q_B y o3 W_E\n"
"qu1 q_B yu1_E\n"
"qu2 q_B yu2_E\n"
"qu3 q_B yu3_E\n"
"qu4 q_B yu4_E\n"
"qu5 q_B yu3_E\n"
"quan1 q_B v A1 N_E\n"
"quan2 q_B v A2 N_E\n"
"quan3 q_B v A3 N_E\n"
"quan4 q_B v A4 N_E\n"
"quan5 q_B v A3 N_E\n"
"que1 q_B v E1_E\n"
"que2 q_B v E2_E\n"
"que3 q_B v E3_E\n"
"que4 q_B v E4_E\n"
"que5 q_B v E3_E\n"
"qun1 q_B v e1 N_E\n"
"qun2 q_B v e2 N_E\n"
"qun3 q_B v e3 N_E\n"
"qun4 q_B v e4 N_E\n"
"qun5 q_B v e3 N_E\n"
"ran1 r_B A1 N_E\n"
"ran2 r_B A2 N_E\n"
"ran3 r_B A3 N_E\n"
"ran4 r_B A4 N_E\n"
"ran5 r_B A3 N_E\n"
"rang1 r_B a1 NG_E\n"
"rang2 r_B a2 NG_E\n"
"rang3 r_B a3 NG_E\n"
"rang4 r_B a4 NG_E\n"
"rang5 r_B a3 NG_E\n"
"rao1 r_B a1 W_E\n"
"rao2 r_B a2 W_E\n"
"rao3 r_B a3 W_E\n"
"rao4 r_B a4 W_E\n"
"rao5 r_B a3 W_E\n"
"re1 r_B e1_E\n"
"re2 r_B e2_E\n"
"re3 r_B e3_E\n"
"re4 r_B e4_E\n"
"re5 r_B e3_E\n"
"ren1 r_B e1 N_E\n"
"ren2 r_B e2 N_E\n"
"ren3 r_B e3 N_E\n"
"ren4 r_B e4 N_E\n"
"ren5 r_B e3 N_E\n"
"reng1 r_B e1 NG_E\n"
"reng2 r_B e2 NG_E\n"
"reng3 r_B e3 NG_E\n"
"reng4 r_B e4 NG_E\n"
"reng5 r_B e3 NG_E\n"
"ri1 r_B IH1_E\n"
"ri2 r_B IH2_E\n"
"ri3 r_B IH3_E\n"
"ri4 r_B IH4_E\n"
"ri5 r_B IH3_E\n"
"rong1 r_B o1 NG_E\n"
"rong2 r_B o2 NG_E\n"
"rong3 r_B o3 NG_E\n"
"rong4 r_B o4 NG_E\n"
"rong5 r_B o3 NG_E\n"
"rou1 r_B o1 W_E\n"
"rou2 r_B o2 W_E\n"
"rou3 r_B o3 W_E\n"
"rou4 r_B o4 W_E\n"
"rou5 r_B o3 W_E\n"
"ru1 r_B u1_E\n"
"ru2 r_B u2_E\n"
"ru3 r_B u3_E\n"
"ru4 r_B u4_E\n"
"ru5 r_B u3_E\n"
"ruan1 r_B w A1 N_E\n"
"ruan2 r_B w A2 N_E\n"
"ruan3 r_B w A3 N_E\n"
"ruan4 r_B w A4 N_E\n"
"ruan5 r_B w A3 N_E\n"
"rui1 r_B w E1 Y_E\n"
"rui2 r_B w E2 Y_E\n"
"rui3 r_B w E3 Y_E\n"
"rui4 r_B w E4 Y_E\n"
"rui5 r_B w E3 Y_E\n"
"run1 r_B w e1 N_E\n"
"run2 r_B w e2 N_E\n"
"run3 r_B w e3 N_E\n"
"run4 r_B w e4 N_E\n"
"run5 r_B w e3 N_E\n"
"ruo1 r_B w o1_E\n"
"ruo2 r_B w o2_E\n"
"ruo3 r_B w o3_E\n"
"ruo4 r_B w o4_E\n"
"ruo5 r_B w o3_E\n"
"sa1 s_B a1_E\n"
"sa2 s_B a2_E\n"
"sa3 s_B a3_E\n"
"sa4 s_B a4_E\n"
"sa5 s_B a3_E\n"
"sai1 s_B A1 Y_E\n"
"sai2 s_B A2 Y_E\n"
"sai3 s_B A3 Y_E\n"
"sai4 s_B A4 Y_E\n"
"sai5 s_B A3 Y_E\n"
"san1 s_B A1 N_E\n"
"san2 s_B A2 N_E\n"
"san3 s_B A3 N_E\n"
"san4 s_B A4 N_E\n"
"san5 s_B A3 N_E\n"
"sang1 s_B a1 NG_E\n"
"sang2 s_B a2 NG_E\n"
"sang3 s_B a3 NG_E\n"
"sang4 s_B a4 NG_E\n"
"sang5 s_B a3 NG_E\n"
"sao1 s_B a1 W_E\n"
"sao2 s_B a2 W_E\n"
"sao3 s_B a3 W_E\n"
"sao4 s_B a4 W_E\n"
"sao5 s_B a3 W_E\n"
"se1 s_B e1_E\n"
"se2 s_B e2_E\n"
"se3 s_B e3_E\n"
"se4 s_B e4_E\n"
"se5 s_B e3_E\n"
"sen1 s_B e1 N_E\n"
"sen2 s_B e2 N_E\n"
"sen3 s_B e3 N_E\n"
"sen4 s_B e4 N_E\n"
"sen5 s_B e3 N_E\n"
"seng1 s_B e1 NG_E\n"
"seng2 s_B e2 NG_E\n"
"seng3 s_B e3 NG_E\n"
"seng4 s_B e4 NG_E\n"
"seng5 s_B e3 NG_E\n"
"sha1 sh_B a1_E\n"
"sha2 sh_B a2_E\n"
"sha3 sh_B a3_E\n"
"sha4 sh_B a4_E\n"
"sha5 sh_B a3_E\n"
"shai1 sh_B A1 Y_E\n"
"shai2 sh_B A2 Y_E\n"
"shai3 sh_B A3 Y_E\n"
"shai4 sh_B A4 Y_E\n"
"shai5 sh_B A3 Y_E\n"
"shan1 sh_B A1 N_E\n"
"shan2 sh_B A2 N_E\n"
"shan3 sh_B A3 N_E\n"
"shan4 sh_B A4 N_E\n"
"shan5 sh_B A3 N_E\n"
"shang1 sh_B a1 NG_E\n"
"shang2 sh_B a2 NG_E\n"
"shang3 sh_B a3 NG_E\n"
"shang4 sh_B a4 NG_E\n"
"shang5 sh_B a3 NG_E\n"
"shao1 sh_B a1 W_E\n"
"shao2 sh_B a2 W_E\n"
"shao3 sh_B a3 W_E\n"
"shao4 sh_B a4 W_E\n"
"shao5 sh_B a3 W_E\n"
"she1 sh_B e1_E\n"
"she2 sh_B e2_E\n"
"she3 sh_B e3_E\n"
"she4 sh_B e4_E\n"
"she5 sh_B e3_E\n"
"shei1 sh_B E1 Y_E\n"
"shei2 sh_B E2 Y_E\n"
"shei3 sh_B E3 Y_E\n"
"shei4 sh_B E4 Y_E\n"
"shei5 sh_B E3 Y_E\n"
"shen1 sh_B e1 N_E\n"
"shen2 sh_B e2 N_E\n"
"shen3 sh_B e3 N_E\n"
"shen4 sh_B e4 N_E\n"
"shen5 sh_B e3 N_E\n"
"sheng1 sh_B e1 NG_E\n"
"sheng2 sh_B e2 NG_E\n"
"sheng3 sh_B e3 NG_E\n"
"sheng4 sh_B e4 NG_E\n"
"sheng5 sh_B e3 NG_E\n"
"shi1 sh_B IH1_E\n"
"shi2 sh_B IH2_E\n"
"shi3 sh_B IH3_E\n"
"shi4 sh_B IH4_E\n"
"shi5 sh_B IH3_E\n"
"shou1 sh_B o1 W_E\n"
"shou2 sh_B o2 W_E\n"
"shou3 sh_B o3 W_E\n"
"shou4 sh_B o4 W_E\n"
"shou5 sh_B o3 W_E\n"
"shu1 sh_B u1_E\n"
"shu2 sh_B u2_E\n"
"shu3 sh_B u3_E\n"
"shu4 sh_B u4_E\n"
"shu5 sh_B u3_E\n"
"shua1 sh_B w a1_E\n"
"shua2 sh_B w a2_E\n"
"shua3 sh_B w a3_E\n"
"shua4 sh_B w a4_E\n"
"shua5 sh_B w a3_E\n"
"shuai1 sh_B w A1 Y_E\n"
"shuai2 sh_B w A2 Y_E\n"
"shuai3 sh_B w A3 Y_E\n"
"shuai4 sh_B w A4 Y_E\n"
"shuai5 sh_B w A3 Y_E\n"
"shuan1 sh_B w A1 N_E\n"
"shuan2 sh_B w A2 N_E\n"
"shuan3 sh_B w A3 N_E\n"
"shuan4 sh_B w A4 N_E\n"
"shuan5 sh_B w A3 N_E\n"
"shuang1 sh_B w a1 NG_E\n"
"shuang2 sh_B w a2 NG_E\n"
"shuang3 sh_B w a3 NG_E\n"
"shuang4 sh_B w a4 NG_E\n"
"shuang5 sh_B w a3 NG_E\n"
"shui1 sh_B w E1 Y_E\n"
"shui2 sh_B w E2 Y_E\n"
"shui3 sh_B w E3 Y_E\n"
"shui4 sh_B w E4 Y_E\n"
"shui5 sh_B w E3 Y_E\n"
"shun1 sh_B w e1 N_E\n"
"shun2 sh_B w e2 N_E\n"
"shun3 sh_B w e3 N_E\n"
"shun4 sh_B w e4 N_E\n"
"shun5 sh_B w e3 N_E\n"
"shuo1 sh_B w o1_E\n"
"shuo2 sh_B w o2_E\n"
"shuo3 sh_B w o3_E\n"
"shuo4 sh_B w o4_E\n"
"shuo5 sh_B w o3_E\n"
"si1 s_B I1_E\n"
"si2 s_B I2_E\n"
"si3 s_B I3_E\n"
"si4 s_B I4_E\n"
"si5 s_B I3_E\n"
"song1 s_B o1 NG_E\n"
"song2 s_B o2 NG_E\n"
"song3 s_B o3 NG_E\n"
"song4 s_B o4 NG_E\n"
"song5 s_B o3 NG_E\n"
"sou1 s_B o1 W_E\n"
"sou2 s_B o2 W_E\n"
"sou3 s_B o3 W_E\n"
"sou4 s_B o4 W_E\n"
"sou5 s_B o3 W_E\n"
"su1 s_B u1_E\n"
"su2 s_B u2_E\n"
"su3 s_B u3_E\n"
"su4 s_B u4_E\n"
"su5 s_B u3_E\n"
"suan1 s_B w A1 N_E\n"
"suan2 s_B w A2 N_E\n"
"suan3 s_B w A3 N_E\n"
"suan4 s_B w A4 N_E\n"
"suan5 s_B w A3 N_E\n"
"sui1 s_B w E1 Y_E\n"
"sui2 s_B w E2 Y_E\n"
"sui3 s_B w E3 Y_E\n"
"sui4 s_B w E4 Y_E\n"
"sui5 s_B w E3 Y_E\n"
"sun1 s_B w e1 N_E\n"
"sun2 s_B w e2 N_E\n"
"sun3 s_B w e3 N_E\n"
"sun4 s_B w e4 N_E\n"
"sun5 s_B w e3 N_E\n"
"suo1 s_B w o1_E\n"
"suo2 s_B w o2_E\n"
"suo3 s_B w o3_E\n"
"suo4 s_B w o4_E\n"
"suo5 s_B w o3_E\n"
"ta1 t_B a1_E\n"
"ta2 t_B a2_E\n"
"ta3 t_B a3_E\n"
"ta4 t_B a4_E\n"
"ta5 t_B a3_E\n"
"tai1 t_B A1 Y_E\n"
"tai2 t_B A2 Y_E\n"
"tai3 t_B A3 Y_E\n"
"tai4 t_B A4 Y_E\n"
"tai5 t_B A3 Y_E\n"
"tan1 t_B A1 N_E\n"
"tan2 t_B A2 N_E\n"
"tan3 t_B A3 N_E\n"
"tan4 t_B A4 N_E\n"
"tan5 t_B A3 N_E\n"
"tang1 t_B a1 NG_E\n"
"tang2 t_B a2 NG_E\n"
"tang3 t_B a3 NG_E\n"
"tang4 t_B a4 NG_E\n"
"tang5 t_B a3 NG_E\n"
"tao1 t_B a1 W_E\n"
"tao2 t_B a2 W_E\n"
"tao3 t_B a3 W_E\n"
"tao4 t_B a4 W_E\n"
"tao5 t_B a3 W_E\n"
"te1 t_B e1_E\n"
"te2 t_B e2_E\n"
"te3 t_B e3_E\n"
"te4 t_B e4_E\n"
"te5 t_B e3_E\n"
"tei1 t_B E1 Y_E\n"
"tei2 t_B E2 Y_E\n"
"tei3 t_B E3 Y_E\n"
"tei4 t_B E4 Y_E\n"
"tei5 t_B E3 Y_E\n"
"teng1 t_B e1 NG_E\n"
"teng2 t_B e2 NG_E\n"
"teng3 t_B e3 NG_E\n"
"teng4 t_B e4 NG_E\n"
"teng5 t_B e3 NG_E\n"
"ti1 t_B i1_E\n"
"ti2 t_B i2_E\n"
"ti3 t_B i3_E\n"
"ti4 t_B i4_E\n"
"ti5 t_B i3_E\n"
"tian1 t_B y A1 N_E\n"
"tian2 t_B y A2 N_E\n"
"tian3 t_B y A3 N_E\n"
"tian4 t_B y A4 N_E\n"
"tian5 t_B y A3 N_E\n"
"tiao1 t_B y a1 W_E\n"
"tiao2 t_B y a2 W_E\n"
"tiao3 t_B y a3 W_E\n"
"tiao4 t_B y a4 W_E\n"
"tiao5 t_B y a3 W_E\n"
"tie1 t_B y E1_E\n"
"tie2 t_B y E2_E\n"
"tie3 t_B y E3_E\n"
"tie4 t_B y E4_E\n"
"tie5 t_B y E3_E\n"
"ting1 t_B i1 NG_E\n"
"ting2 t_B i2 NG_E\n"
"ting3 t_B i3 NG_E\n"
"ting4 t_B i4 NG_E\n"
"ting5 t_B i3 NG_E\n"
"tong1 t_B o1 NG_E\n"
"tong2 t_B o2 NG_E\n"
"tong3 t_B o3 NG_E\n"
"tong4 t_B o4 NG_E\n"
"tong5 t_B o3 NG_E\n"
"tou1 t_B o1 W_E\n"
"tou2 t_B o2 W_E\n"
"tou3 t_B o3 W_E\n"
"tou4 t_B o4 W_E\n"
"tou5 t_B o3 W_E\n"
"tu1 t_B u1_E\n"
"tu2 t_B u2_E\n"
"tu3 t_B u3_E\n"
"tu4 t_B u4_E\n"
"tu5 t_B u3_E\n"
"tuan1 t_B w A1 N_E\n"
"tuan2 t_B w A2 N_E\n"
"tuan3 t_B w A3 N_E\n"
"tuan4 t_B w A4 N_E\n"
"tuan5 t_B w A3 N_E\n"
"tui1 t_B w E1 Y_E\n"
"tui2 t_B w E2 Y_E\n"
"tui3 t_B w E3 Y_E\n"
"tui4 t_B w E4 Y_E\n"
"tui5 t_B w E3 Y_E\n"
"tun1 t_B w e1 N_E\n"
"tun2 t_B w e2 N_E\n"
"tun3 t_B w e3 N_E\n"
"tun4 t_B w e4 N_E\n"
"tun5 t_B w e3 N_E\n"
"tuo1 t_B w o1_E\n"
"tuo2 t_B w o2_E\n"
"tuo3 t_B w o3_E\n"
"tuo4 t_B w o4_E\n"
"tuo5 t_B w o3_E\n"
"wa1 w_B a1_E\n"
"wa2 w_B a2_E\n"
"wa3 w_B a3_E\n"
"wa4 w_B a4_E\n"
"wa5 w_B a3_E\n"
"wai1 w_B A1 Y_E\n"
"wai2 w_B A2 Y_E\n"
"wai3 w_B A3 Y_E\n"
"wai4 w_B A4 Y_E\n"
"wai5 w_B A3 Y_E\n"
"wan1 w_B A1 N_E\n"
"wan2 w_B A2 N_E\n"
"wan3 w_B A3 N_E\n"
"wan4 w_B A4 N_E\n"
"wan5 w_B A3 N_E\n"
"wang1 w_B a1 NG_E\n"
"wang2 w_B a2 NG_E\n"
"wang3 w_B a3 NG_E\n"
"wang4 w_B a4 NG_E\n"
"wang5 w_B a3 NG_E\n"
"wei1 w_B E1 Y_E\n"
"wei2 w_B E2 Y_E\n"
"wei3 w_B E3 Y_E\n"
"wei4 w_B E4 Y_E\n"
"wei5 w_B E3 Y_E\n"
"wen1 w_B e1 N_E\n"
"wen2 w_B e2 N_E\n"
"wen3 w_B e3 N_E\n"
"wen4 w_B e4 N_E\n"
"wen5 w_B e3 N_E\n"
"weng1 w_B e1 NG_E\n"
"weng2 w_B e2 NG_E\n"
"weng3 w_B e3 NG_E\n"
"weng4 w_B e4 NG_E\n"
"weng5 w_B e3 NG_E\n"
"wo1 w_B o1_E\n"
"wo2 w_B o2_E\n"
"wo3 w_B o3_E\n"
"wo4 w_B o4_E\n"
"wo5 w_B o3_E\n"
"wu1 w_B u1_E\n"
"wu2 w_B u2_E\n"
"wu3 w_B u3_E\n"
"wu4 w_B u4_E\n"
"wu5 w_B u3_E\n"
"xi1 x_B i1_E\n"
"xi2 x_B i2_E\n"
"xi3 x_B i3_E\n"
"xi4 x_B i4_E\n"
"xi5 x_B i3_E\n"
"xia1 x_B y A1_E\n"
"xia2 x_B y A2_E\n"
"xia3 x_B y A3_E\n"
"xia4 x_B y A4_E\n"
"xia5 x_B y A3_E\n"
"xian1 x_B y A1 N_E\n"
"xian2 x_B y A2 N_E\n"
"xian3 x_B y A3 N_E\n"
"xian4 x_B y A4 N_E\n"
"xian5 x_B y A3 N_E\n"
"xiang1 x_B y a1 NG_E\n"
"xiang2 x_B y a2 NG_E\n"
"xiang3 x_B y a3 NG_E\n"
"xiang4 x_B y a4 NG_E\n"
"xiang5 x_B y a3 NG_E\n"
"xiao1 x_B y a1 W_E\n"
"xiao2 x_B y a2 W_E\n"
"xiao3 x_B y a3 W_E\n"
"xiao4 x_B y a4 W_E\n"
"xiao5 x_B y a3 W_E\n"
"xie1 x_B y E1_E\n"
"xie2 x_B y E2_E\n"
"xie3 x_B y E3_E\n"
"xie4 x_B y E4_E\n"
"xie5 x_B y E3_E\n"
"xin1 x_B i1 N_E\n"
"xin2 x_B i2 N_E\n"
"xin3 x_B i3 N_E\n"
"xin4 x_B i4 N_E\n"
"xin5 x_B i3 N_E\n"
"xing1 x_B i1 NG_E\n"
"xing2 x_B i2 NG_E\n"
"xing3 x_B i3 NG_E\n"
"xing4 x_B i4 NG_E\n"
"xing5 x_B i3 NG_E\n"
"xiong1 x_B y o1 NG_E\n"
"xiong2 x_B y o2 NG_E\n"
"xiong3 x_B y o3 NG_E\n"
"xiong4 x_B y o4 NG_E\n"
"xiong5 x_B y o3 NG_E\n"
"xiu1 x_B y o1 W_E\n"
"xiu2 x_B y o2 W_E\n"
"xiu3 x_B y o3 W_E\n"
"xiu4 x_B y o4 W_E\n"
"xiu5 x_B y o3 W_E\n"
"xu1 x_B yu1_E\n"
"xu2 x_B yu2_E\n"
"xu3 x_B yu3_E\n"
"xu4 x_B yu4_E\n"
"xu5 x_B yu3_E\n"
"xuan1 x_B v A1 N_E\n"
"xuan2 x_B v A2 N_E\n"
"xuan3 x_B v A3 N_E\n"
"xuan4 x_B v A4 N_E\n"
"xuan5 x_B v A3 N_E\n"
"xue1 x_B v E1_E\n"
"xue2 x_B v E2_E\n"
"xue3 x_B v E3_E\n"
"xue4 x_B v E4_E\n"
"xue5 x_B v E3_E\n"
"xun1 x_B v e1 N_E\n"
"xun2 x_B v e2 N_E\n"
"xun3 x_B v e3 N_E\n"
"xun4 x_B v e4 N_E\n"
"xun5 x_B v e3 N_E\n"
"ya1 y_B A1_E\n"
"ya2 y_B A2_E\n"
"ya3 y_B A3_E\n"
"ya4 y_B A4_E\n"
"ya5 y_B A3_E\n"
"yan1 y_B A1 N_E\n"
"yan2 y_B A2 N_E\n"
"yan3 y_B A3 N_E\n"
"yan4 y_B A4 N_E\n"
"yan5 y_B A3 N_E\n"
"yang1 y_B a1 NG_E\n"
"yang2 y_B a2 NG_E\n"
"yang3 y_B a3 NG_E\n"
"yang4 y_B a4 NG_E\n"
"yang5 y_B a3 NG_E\n"
"yao1 y_B a1 W_E\n"
"yao2 y_B a2 W_E\n"
"yao3 y_B a3 W_E\n"
"yao4 y_B a4 W_E\n"
"yao5 y_B a3 W_E\n"
"ye1 y_B E1_E\n"
"ye2 y_B E2_E\n"
"ye3 y_B E3_E\n"
"ye4 y_B E4_E\n"
"ye5 y_B E3_E\n"
"yi1 y_B i1_E\n"
"yi2 y_B i2_E\n"
"yi3 y_B i3_E\n"
"yi4 y_B i4_E\n"
"yi5 y_B i3_E\n"
"yin1 y_B i1 N_E\n"
"yin2 y_B i2 N_E\n"
"yin3 y_B i3 N_E\n"
"yin4 y_B i4 N_E\n"
"yin5 y_B i3 N_E\n"
"ying1 y_B i1 NG_E\n"
"ying2 y_B i2 NG_E\n"
"ying3 y_B i3 NG_E\n"
"ying4 y_B i4 NG_E\n"
"ying5 y_B i3 NG_E\n"
"yo1 y_B o1_E\n"
"yo2 y_B o2_E\n"
"yo3 y_B o3_E\n"
"yo4 y_B o4_E\n"
"yo5 y_B o3_E\n"
"yong1 y_B o1 NG_E\n"
"yong2 y_B o2 NG_E\n"
"yong3 y_B o3 NG_E\n"
"yong4 y_B o4 NG_E\n"
"yong5 y_B o3 NG_E\n"
"you1 y_B o1 W_E\n"
"you2 y_B o2 W_E\n"
"you3 y_B o3 W_E\n"
"you4 y_B o4 W_E\n"
"you5 y_B o3 W_E\n"
"yu1 v_B yu1_E\n"
"yu2 v_B yu2_E\n"
"yu3 v_B yu3_E\n"
"yu4 v_B yu4_E\n"
"yu5 v_B yu3_E\n"
"yuan1 v_B A1 N_E\n"
"yuan2 v_B A2 N_E\n"
"yuan3 v_B A3 N_E\n"
"yuan4 v_B A4 N_E\n"
"yuan5 v_B A3 N_E\n"
"yue1 v_B E1_E\n"
"yue2 v_B E2_E\n"
"yue3 v_B E3_E\n"
"yue4 v_B E4_E\n"
"yue5 v_B E3_E\n"
"yun1 v_B e1 N_E\n"
"yun2 v_B e2 N_E\n"
"yun3 v_B e3 N_E\n"
"yun4 v_B e4 N_E\n"
"yun5 v_B e3 N_E\n"
"za1 z_B a1_E\n"
"za2 z_B a2_E\n"
"za3 z_B a3_E\n"
"za4 z_B a4_E\n"
"za5 z_B a3_E\n"
"zai1 z_B A1 Y_E\n"
"zai2 z_B A2 Y_E\n"
"zai3 z_B A3 Y_E\n"
"zai4 z_B A4 Y_E\n"
"zai5 z_B A3 Y_E\n"
"zan1 z_B A1 N_E\n"
"zan2 z_B A2 N_E\n"
"zan3 z_B A3 N_E\n"
"zan4 z_B A4 N_E\n"
"zan5 z_B A3 N_E\n"
"zang1 z_B a1 NG_E\n"
"zang2 z_B a2 NG_E\n"
"zang3 z_B a3 NG_E\n"
"zang4 z_B a4 NG_E\n"
"zang5 z_B a3 NG_E\n"
"zao1 z_B a1 W_E\n"
"zao2 z_B a2 W_E\n"
"zao3 z_B a3 W_E\n"
"zao4 z_B a4 W_E\n"
"zao5 z_B a3 W_E\n"
"ze1 z_B e1_E\n"
"ze2 z_B e2_E\n"
"ze3 z_B e3_E\n"
"ze4 z_B e4_E\n"
"ze5 z_B e3_E\n"
"zei1 z_B E1 Y_E\n"
"zei2 z_B E2 Y_E\n"
"zei3 z_B E3 Y_E\n"
"zei4 z_B E4 Y_E\n"
"zei5 z_B E3 Y_E\n"
"zen1 z_B e1 N_E\n"
"zen2 z_B e2 N_E\n"
"zen3 z_B e3 N_E\n"
"zen4 z_B e4 N_E\n"
"zen5 z_B e3 N_E\n"
"zeng1 z_B e1 NG_E\n"
"zeng2 z_B e2 NG_E\n"
"zeng3 z_B e3 NG_E\n"
"zeng4 z_B e4 NG_E\n"
"zeng5 z_B e3 NG_E\n"
"zha1 zh_B a1_E\n"
"zha2 zh_B a2_E\n"
"zha3 zh_B a3_E\n"
"zha4 zh_B a4_E\n"
"zha5 zh_B a3_E\n"
"zhai1 zh_B A1 Y_E\n"
"zhai2 zh_B A2 Y_E\n"
"zhai3 zh_B A3 Y_E\n"
"zhai4 zh_B A4 Y_E\n"
"zhai5 zh_B A3 Y_E\n"
"zhan1 zh_B A1 N_E\n"
"zhan2 zh_B A2 N_E\n"
"zhan3 zh_B A3 N_E\n"
"zhan4 zh_B A4 N_E\n"
"zhan5 zh_B A3 N_E\n"
"zhang1 zh_B a1 NG_E\n"
"zhang2 zh_B a2 NG_E\n"
"zhang3 zh_B a3 NG_E\n"
"zhang4 zh_B a4 NG_E\n"
"zhang5 zh_B a3 NG_E\n"
"zhao1 zh_B a1 W_E\n"
"zhao2 zh_B a2 W_E\n"
"zhao3 zh_B a3 W_E\n"
"zhao4 zh_B a4 W_E\n"
"zhao5 zh_B a3 W_E\n"
"zhe1 zh_B e1_E\n"
"zhe2 zh_B e2_E\n"
"zhe3 zh_B e3_E\n"
"zhe4 zh_B e4_E\n"
"zhe5 zh_B e3_E\n"
"zhen1 zh_B e1 N_E\n"
"zhen2 zh_B e2 N_E\n"
"zhen3 zh_B e3 N_E\n"
"zhen4 zh_B e4 N_E\n"
"zhen5 zh_B e3 N_E\n"
"zheng1 zh_B e1 NG_E\n"
"zheng2 zh_B e2 NG_E\n"
"zheng3 zh_B e3 NG_E\n"
"zheng4 zh_B e4 NG_E\n"
"zheng5 zh_B e3 NG_E\n"
"zhi1 zh_B IH1_E\n"
"zhi2 zh_B IH2_E\n"
"zhi3 zh_B IH3_E\n"
"zhi4 zh_B IH4_E\n"
"zhi5 zh_B IH3_E\n"
"zhong1 zh_B o1 NG_E\n"
"zhong2 zh_B o2 NG_E\n"
"zhong3 zh_B o3 NG_E\n"
"zhong4 zh_B o4 NG_E\n"
"zhong5 zh_B o3 NG_E\n"
"zhou1 zh_B o1 W_E\n"
"zhou2 zh_B o2 W_E\n"
"zhou3 zh_B o3 W_E\n"
"zhou4 zh_B o4 W_E\n"
"zhou5 zh_B o3 W_E\n"
"zhu1 zh_B u1_E\n"
"zhu2 zh_B u2_E\n"
"zhu3 zh_B u3_E\n"
"zhu4 zh_B u4_E\n"
"zhu5 zh_B u3_E\n"
"zhua1 zh_B w a1_E\n"
"zhua2 zh_B w a2_E\n"
"zhua3 zh_B w a3_E\n"
"zhua4 zh_B w a4_E\n"
"zhua5 zh_B w a3_E\n"
"zhuai1 zh_B w A1 Y_E\n"
"zhuai2 zh_B w A2 Y_E\n"
"zhuai3 zh_B w A3 Y_E\n"
"zhuai4 zh_B w A4 Y_E\n"
"zhuai5 zh_B w A3 Y_E\n"
"zhuan1 zh_B w A1 N_E\n"
"zhuan2 zh_B w A2 N_E\n"
"zhuan3 zh_B w A3 N_E\n"
"zhuan4 zh_B w A4 N_E\n"
"zhuan5 zh_B w A3 N_E\n"
"zhuang1 zh_B w a1 NG_E\n"
"zhuang2 zh_B w a2 NG_E\n"
"zhuang3 zh_B w a3 NG_E\n"
"zhuang4 zh_B w a4 NG_E\n"
"zhuang5 zh_B w a3 NG_E\n"
"zhui1 zh_B w E1 Y_E\n"
"zhui2 zh_B w E2 Y_E\n"
"zhui3 zh_B w E3 Y_E\n"
"zhui4 zh_B w E4 Y_E\n"
"zhui5 zh_B w E3 Y_E\n"
"zhun1 zh_B w e1 N_E\n"
"zhun2 zh_B w e2 N_E\n"
"zhun3 zh_B w e3 N_E\n"
"zhun4 zh_B w e4 N_E\n"
"zhun5 zh_B w e3 N_E\n"
"zhuo1 zh_B w o1_E\n"
"zhuo2 zh_B w o2_E\n"
"zhuo3 zh_B w o3_E\n"
"zhuo4 zh_B w o4_E\n"
"zhuo5 zh_B w o3_E\n"
"zi1 z_B I1_E\n"
"zi2 z_B I2_E\n"
"zi3 z_B I3_E\n"
"zi4 z_B I4_E\n"
"zi5 z_B I3_E\n"
"zong1 z_B o1 NG_E\n"
"zong2 z_B o2 NG_E\n"
"zong3 z_B o3 NG_E\n"
"zong4 z_B o4 NG_E\n"
"zong5 z_B o3 NG_E\n"
"zou1 z_B o1 W_E\n"
"zou2 z_B o2 W_E\n"
"zou3 z_B o3 W_E\n"
"zou4 z_B o4 W_E\n"
"zou5 z_B o3 W_E\n"
"zu1 z_B u1_E\n"
"zu2 z_B u2_E\n"
"zu3 z_B u3_E\n"
"zu4 z_B u4_E\n"
"zu5 z_B u3_E\n"
"zuan1 z_B w A1 N_E\n"
"zuan2 z_B w A2 N_E\n"
"zuan3 z_B w A3 N_E\n"
"zuan4 z_B w A4 N_E\n"
"zuan5 z_B w A3 N_E\n"
"zui1 z_B w E1 Y_E\n"
"zui2 z_B w E2 Y_E\n"
"zui3 z_B w E3 Y_E\n"
"zui4 z_B w E4 Y_E\n"
"zui5 z_B w E3 Y_E\n"
"zun1 z_B w e1 N_E\n"
"zun2 z_B w e2 N_E\n"
"zun3 z_B w e3 N_E\n"
"zun4 z_B w e4 N_E\n"
"zun5 z_B w e3 N_E\n"
"zuo1 z_B w o1_E\n"
"zuo2 z_B w o2_E\n"
"zuo3 z_B w o3_E\n"
"zuo4 z_B w o4_E\n"
"zuo5 z_B w o3_E\n";

#endif /* PHONES_H */
